import { Group } from './types';

export const GROUPS: Group[] = [
  {
    id: 1,
    title: "INSPECTION & VERIFICATION",
    desc: "Examine, measure and confirm conditions",
    color: "#003366",
    words: [
      { en: "ADD", es: "Agregar", ctx: "ADD 5 ml OF HARDENER TO THE COMPOUND.", ctxEs: "Agregue 5 ml de endurecedor al compuesto." },
      { en: "ADJUST", es: "Ajustar", ctx: "ADJUST THE FREQUENCY TO THE VALUE GIVEN IN TABLE 1.", ctxEs: "Ajuste la frecuencia al valor dado en la Tabla 1." },
      { en: "ALIGN", es: "Alinear", ctx: "ALIGN THE FLANGE HOLES WITH THE STUDS.", ctxEs: "Alinee los agujeros de la brida con los espárragos." },
      { en: "APPLY", es: "Aplicar", ctx: "APPLY A FORCE OF 100 N ON THE END OF THE LEVER.", ctxEs: "Aplique una fuerza de 100 N en el extremo de la palanca." },
      { en: "ASSEMBLE", es: "Ensamblar", ctx: "ASSEMBLE THE VALVE AS FOLLOWS:", ctxEs: "Ensamble la válvula de la siguiente manera:" },
      { en: "ATTACH", es: "Fijar/Unir", ctx: "ATTACH THE TWO STRINGERS TOGETHER WITH RIVETS.", ctxEs: "Una los dos largueros entre sí con remaches." },
      { en: "BLEED", es: "Purgar/Sangrar", ctx: "BLEED THE SPEEDBRAKE HYDRAULIC SYSTEM.", ctxEs: "Purgue el sistema hidráulico del spoiler de velocidad." },
      { en: "BOND", es: "Unir/Conectar eléctricamente", ctx: "THE STATIC DISCHARGER IS ELECTRICALLY BONDED TO THE FRAME.", ctxEs: "El disipador estático está unido eléctricamente al marco." },
      { en: "CALCULATE", es: "Calcular", ctx: "CALCULATE THE PRESSURE WITH THE APPLICABLE FORMULA.", ctxEs: "Calcule la presión con la fórmula aplicable." },
      { en: "CALIBRATE", es: "Calibrar", ctx: "CALIBRATE THE THERMOMETER TO THE CELSIUS SCALE.", ctxEs: "Calibre el termómetro a la escala Celsius." },
      { en: "CANCEL", es: "Cancelar", ctx: "CANCEL THE NAV 1 FAULT INDICATION AND USE THE NAV 2 SYSTEM.", ctxEs: "Cancele la indicación de falla de NAV 1 y use el sistema NAV 2." },
      { en: "CHECK", es: "Verificar", ctx: "CHECK THAT IT IS SAFE TO APPLY ELECTRICAL POWER.", ctxEs: "Verifique que sea seguro aplicar energía eléctrica." },
      { en: "CLEAN", es: "Limpiar", ctx: "CLEAN THE GASKET CONTACT SURFACE.", ctxEs: "Limpie la superficie de contacto de la junta." },
      { en: "CLOSE", es: "Cerrar", ctx: "CLOSE THE INSTRUMENT PANEL.", ctxEs: "Cierre el panel de instrumentos." },
      { en: "CONNECT", es: "Conectar", ctx: "CONNECT THE ELECTRICAL CONNECTORS TO THE INSTRUMENT.", ctxEs: "Conecte los conectores eléctricos al instrumento." },
      { en: "CUT", es: "Cortar", ctx: "CUT THE CABLE INTO THREE EQUAL LENGTHS.", ctxEs: "Corte el cable en tres longitudes iguales." },
      { en: "DECREASE", es: "Disminuir", ctx: "DECREASE THE HEADING INDICATIONS.", ctxEs: "Disminuya las indicaciones de rumbo." },
      { en: "DISCONNECT", es: "Desconectar", ctx: "DISCONNECT THE POWER SUPPLY.", ctxEs: "Desconecte el suministro de energía." }
    ]
  },
  {
    id: 2,
    title: "INSTALLATION & ASSEMBLY",
    desc: "Fix, connect and assemble components",
    color: "#1a5276",
    words: [
      { en: "DRAIN", es: "Drenar", ctx: "DRAIN THE SYSTEM FULLY.", ctxEs: "Drene el sistema completamente." },
      { en: "ENGAGE", es: "Acoplar/Enganchar", ctx: "ENGAGE THE CLUTCH.", ctxEs: "Acople el embrague." },
      { en: "EXAMINE", es: "Examinar", ctx: "EXAMINE THE COMPUTER FOR DAMAGE.", ctxEs: "Examine la computadora en busca de daños." },
      { en: "EXTEND", es: "Extender", ctx: "FULLY EXTEND THE JACK RAM.", ctxEs: "Extienda completamente el pistón del gato." },
      { en: "FILL", es: "Llenar", ctx: "FILL THE TANK WITH METHANOL.", ctxEs: "Llene el tanque con metanol." },
      { en: "FIND", es: "Encontrar", ctx: "YOU CAN FIND THE NUMBERS ON THE SWITCH.", ctxEs: "Puede encontrar los números en el interruptor." },
      { en: "FLUSH", es: "Enjuagar/Limpiar a presión", ctx: "FLUSH THE TUBES WITH PRESSURIZED FUEL.", ctxEs: "Enjuague los tubos con combustible presurizado." },
      { en: "GET", es: "Obtener/Recibir", ctx: "IF YOU GET THE FLUID ON YOUR SKIN, FLUSH YOUR SKIN IMMEDIATELY WITH CLEAN WATER.", ctxEs: "Si recibe fluido en la piel, enjuáguela inmediatamente con agua limpia." },
      { en: "GIVE", es: "Dar/Proporcionar", ctx: "THIS SECTION GIVES YOU THE PROCEDURES FOR THE DISASSEMBLY.", ctxEs: "Esta sección le proporciona los procedimientos para el desensamblaje." },
      { en: "HOLD", es: "Sostener", ctx: "HOLD THE ROD TIGHTLY.", ctxEs: "Sostenga la varilla firmemente." },
      { en: "IDENTIFY", es: "Identificar", ctx: "IDENTIFY THE WIRES WITH SLEEVES OF DIFFERENT COLORS.", ctxEs: "Identifique los cables con fundas de diferentes colores." },
      { en: "INCREASE", es: "Aumentar", ctx: "INCREASE THE VANE ANGLE TO 90 DEGREES.", ctxEs: "Aumente el ángulo de la paleta a 90 grados." },
      { en: "INSTALL", es: "Instalar", ctx: "INSTALL THE NEW O-RINGS ON THE SPINDLE.", ctxEs: "Instale las nuevas juntas tóricas en el eje." },
      { en: "ISOLATE", es: "Aislar", ctx: "ISOLATE THE ELECTRICAL POWER SUPPLY.", ctxEs: "Aísle el suministro de energía eléctrica." },
      { en: "KEEP", es: "Mantener/Guardar", ctx: "KEEP THE COMPOUND IN A CLOSED CONTAINER.", ctxEs: "Mantenga el compuesto en un recipiente cerrado." },
      { en: "LET", es: "Permitir/Dejar", ctx: "LET THE ADHESIVE BECOME TACKY.", ctxEs: "Deje que el adhesivo se vuelva pegajoso." },
      { en: "LIFT", es: "Levantar", ctx: "LIFT THE COVER CAREFULLY.", ctxEs: "Levante la cubierta cuidadosamente." },
      { en: "LOCK", es: "Bloquear", ctx: "LOCK THE SWITCH AND REMOVE THE KEY.", ctxEs: "Bloquee el interruptor y retire la llave." }
    ]
  },
  {
    id: 3,
    title: "REMOVAL & DISASSEMBLY",
    desc: "Separate, disconnect and remove components",
    color: "#7b241c",
    words: [
      { en: "LOOSEN", es: "Aflojar", ctx: "LOOSEN THE SCREWS THAT ATTACH THE CLAMP TO THE SUPPORT.", ctxEs: "Afloje los tornillos que fijan la abrazadera al soporte." },
      { en: "LUBRICATE", es: "Lubricar", ctx: "LUBRICATE THE O-RINGS WITH HYDRAULIC FLUID (NATO CODE H-515).", ctxEs: "Lubrique las juntas tóricas con fluido hidráulico (Código OTAN H-515)." },
      { en: "MAKE", es: "Hacer/Crear", ctx: "MAKE A RECESS FOR THE STUDS OF 5 mm.", ctxEs: "Haga un rebaje para los espárragos de 5 mm." },
      { en: "MAKE SURE", es: "Asegurarse", ctx: "MAKE SURE THAT NO LEAK DETECTION FLUID GOES INTO THE OXYGEN SYSTEM.", ctxEs: "Asegúrese de que no entre fluido detector de fugas al sistema de oxígeno." },
      { en: "MEASURE", es: "Medir", ctx: "MEASURE THE LOAD.", ctxEs: "Mida la carga." },
      { en: "MIX", es: "Mezclar", ctx: "MIX THE COMPOUND FULLY.", ctxEs: "Mezcle el compuesto completamente." },
      { en: "MONITOR", es: "Monitorear", ctx: "MONITOR THE INDICATORS ON THE OVERHEAD PANEL.", ctxEs: "Monitoree los indicadores en el panel superior." },
      { en: "MOVE", es: "Mover", ctx: "MOVE THE VALVE UNTIL IT ALIGNS WITH THE ACTUATOR SHAFT.", ctxEs: "Mueva la válvula hasta que se alinee con el eje del actuador." },
      { en: "OPERATE", es: "Operar", ctx: "OPERATE THE PLUNGER TO DRAIN THE SYSTEM.", ctxEs: "Opere el émbolo para drenar el sistema." },
      { en: "OPEN", es: "Abrir", ctx: "OPEN THE PRESSURE VALVE.", ctxEs: "Abra la válvula de presión." },
      { en: "PAINT", es: "Pintar", ctx: "PAINT ALL THE SURFACES.", ctxEs: "Pinte todas las superficies." },
      { en: "PERFORM", es: "Realizar", ctx: "DO THE LEAK TEST.", ctxEs: "Realice la prueba de fugas." },
      { en: "PLACE", es: "Colocar", ctx: "PLACE THE MANIFOLD IN POSITION.", ctxEs: "Coloque el múltiple en posición." },
      { en: "POINT", es: "Apuntar", ctx: "MAKE SURE THAT THE ARROW ON THE CHECK VALVE POINTS AWAY FROM THE GROUND SUPPLY DUCT.", ctxEs: "Asegúrese de que la flecha en la válvula de retención apunte lejos del conducto de suministro terrestre." },
      { en: "PREVENT", es: "Prevenir", ctx: "TO PREVENT DAMAGE TO THE ENGINE, IMMEDIATELY INSTALL PROTECTIVE COVERS ON ALL OPENINGS.", ctxEs: "Para prevenir daños al motor, instale inmediatamente cubiertas protectoras en todas las aberturas." },
      { en: "PULL", es: "Jalar/Tirar", ctx: "PULL THE PEDESTAL AWAY FROM THE MOUNTING.", ctxEs: "Jale el pedestal alejándolo del montaje." },
      { en: "PUSH", es: "Empujar", ctx: "PUSH THE INSERT UNTIL IT TOUCHES THE BOTTOM OF THE HOLE.", ctxEs: "Empuje el inserto hasta que toque el fondo del agujero." },
      { en: "PUT", es: "Poner/Colocar", ctx: "PUT THE ADAPTER IN POSITION AGAINST ITS SUPPORT.", ctxEs: "Coloque el adaptador en posición contra su soporte." }
    ]
  },
  {
    id: 4,
    title: "ADJUSTMENT & CALIBRATION",
    desc: "Regulate, configure and set precise values",
    color: "#1e8449",
    words: [
      { en: "READ", es: "Leer", ctx: "READ THE INDICATORS ON THE CONTROL PANEL.", ctxEs: "Lea los indicadores en el panel de control." },
      { en: "RECORD", es: "Registrar", ctx: "RECORD THE RESULTS.", ctxEs: "Registre los resultados." },
      { en: "RELEASE", es: "Liberar/Soltar", ctx: "RELEASE THE INSTRUMENT PANEL TO GET ACCESS TO THE CONNECTIONS.", ctxEs: "Suelte el panel de instrumentos para acceder a las conexiones." },
      { en: "REMOVE", es: "Remover/Retirar", ctx: "REMOVE THE INDICATOR FROM THE PANEL.", ctxEs: "Retire el indicador del panel." },
      { en: "REPLACE", es: "Reemplazar", ctx: "REPLACE THE RELAY.", ctxEs: "Reemplace el relé." },
      { en: "REPAIR", es: "Reparar", ctx: "REPAIR THE DEFECTIVE WIRING.", ctxEs: "Repare el cableado defectuoso." },
      { en: "RESET", es: "Restablecer", ctx: "RESET THE INDICATOR TO A NEW POSITION.", ctxEs: "Restablezca el indicador a una nueva posición." },
      { en: "RESTRICT", es: "Restringir", ctx: "RESTRICT THE use OF THESE NUTS TO TEST ONLY.", ctxEs: "Restrinja el uso de estas tuercas solo para pruebas." },
      { en: "RETRACT", es: "Retraer", ctx: "RETRACT THE LANDING GEAR.", ctxEs: "Retraiga el tren de aterrizaje." },
      { en: "ROUTE", es: "Enrutar/Colocar", ctx: "ROUTE THE FUELING HOSE ALONG THE GROUND.", ctxEs: "Coloque la manguera de combustible a lo largo del suelo." },
      { en: "RUN", es: "Ejecutar/Operar", ctx: "RUN THE ENGINE AT 100% THRUST.", ctxEs: "Opere el motor al 100% de empuje." },
      { en: "SAFETY", es: "Asegurar/Inmovilizar", ctx: "TAG AND SAFETY THE CIRCUIT BREAKERS.", ctxEs: "Etiquete y asegure los interruptores automáticos." },
      { en: "SEAL", es: "Sellar", ctx: "SEAL THE OPENINGS WITH POLYETHYLENE.", ctxEs: "Selle las aberturas con polietileno." },
      { en: "SEARCH", es: "Buscar/Examinar", ctx: "SEARCH THE SURFACE FOR CRACKS.", ctxEs: "Examine la superficie en busca de grietas." },
      { en: "SELECT", es: "Seleccionar", ctx: "SELECT THE HYDRAULIC SYSTEM THAT YOU WILL PRESSURIZE.", ctxEs: "Seleccione el sistema hidráulico que presurizará." },
      { en: "SEND", es: "Enviar", ctx: "SEND THE FILTER ELEMENT TO THE OVERHAUL SHOP.", ctxEs: "Envíe el elemento filtrante al taller de revisión general." },
      { en: "SET", es: "Ajustar/Configurar", ctx: "SET THE ALTIMETER SCALE TO 1013 mbar.", ctxEs: "Ajuste la escala del altímetro a 1013 mbar." },
      { en: "SHOW", es: "Mostrar", ctx: "THE INDICATOR SHOWS THE LEVEL OF HYDRAULIC FLUID IN THE RESERVOIR.", ctxEs: "El indicador muestra el nivel de fluido hidráulico en el depósito." }
    ]
  },
  {
    id: 5,
    title: "OPERATION & CONTROL",
    desc: "Activate, handle and control systems",
    color: "#6c3483",
    words: [
      { en: "START", es: "Arrancar/Iniciar", ctx: "START THE ENGINE.", ctxEs: "Arranque el motor." },
      { en: "STOP", es: "Detener", ctx: "STOP THE ENGINE.", ctxEs: "Detenga el motor." },
      { en: "STORE", es: "Almacenar", ctx: "STORE THE CARTRIDGES IN A SAFETY AREA.", ctxEs: "Almacene los cartuchos en un área segura." },
      { en: "SUPPLY", es: "Suministrar", ctx: "SUPPLY ELECTRICAL POWER TO THE PUMPS.", ctxEs: "Suministre energía eléctrica a las bombas." },
      { en: "TIGHTEN", es: "Apretar", ctx: "TIGHTEN THE SCREWS.", ctxEs: "Apriete los tornillos." },
      { en: "TORQUE", es: "Aplicar par de torsión", ctx: "TORQUE THE PLUG TO 6 Nm.", ctxEs: "Aplique un par de torsión de 6 Nm al tapón." },
      { en: "TURN", es: "Girar", ctx: "TURN THE CONTROL CLOCKWISE.", ctxEs: "Gire el control en sentido horario." },
      { en: "UNLOCK", es: "Desbloquear", ctx: "MAKE SURE THAT THE CABIN DIFFERENTIAL PRESSURE IS ZERO BEFORE YOU UNLOCK THE DOOR.", ctxEs: "Asegúrese de que la presión diferencial de la cabina sea cero antes de desbloquear la puerta." },
      { en: "USE", es: "Usar", ctx: "USE THE TEST BOX TO DO A TEST ON THE SYSTEM.", ctxEs: "Use la caja de pruebas para realizar una prueba en el sistema." },
      { en: "VERIFY", es: "Verificar", ctx: "VERIFY THE TIGHTNESS OF FITTINGS.", ctxEs: "Verifique el apriete de las conexiones." },
      { en: "WAIT", es: "Esperar", ctx: "WAIT FOR 4 MINUTES.", ctxEs: "Espere 4 minutos." },
      { en: "WASH", es: "Lavar", ctx: "WASH YOUR HANDS USING SOAP.", ctxEs: "Lave sus manos usando jabón." },
      { en: "WEIGH", es: "Pesar", ctx: "WEIGH THE TWO PARTS OF THE COMPOUND.", ctxEs: "Pese las dos partes del compuesto." },
      { en: "WIND", es: "Enrollar", ctx: "WIND THE TAPE ON THE REEL.", ctxEs: "Enrolle la cinta en el carrete." },
      { en: "WRITE", es: "Escribir", ctx: "WRITE THE TEST DATE ON THE CERTIFICATE.", ctxEs: "Escriba la fecha de la prueba en el certificado." },
      { en: "ZERO", es: "Poner a cero", ctx: "ZERO THE METER.", ctxEs: "Ponga a cero el medidor." },
      { en: "ACTIVATE", es: "Activar", ctx: "ACTIVATE THE MOTOR.", ctxEs: "Active el motor." },
      { en: "ADAPT", es: "Adaptar", ctx: "ADAPT THE PRESSURE CONNECTION TO THE PITOT HEAD.", ctxEs: "Adapte la conexión de presión al cabezal Pitot." }
    ]
  },
  {
    id: 6,
    title: "CLEANING & MAINTENANCE",
    desc: "Clean, lubricate and preserve components",
    color: "#117a65",
    words: [
      { en: "ADHERE", es: "Adherir", ctx: "ADHERE THE SEAL PERMANENTLY.", ctxEs: "Adhiera el sello permanentemente." },
      { en: "AGREE", es: "Coincidir/Concordar", ctx: "THE INDICATIONS MUST AGREE WITH THE VALUES IN THE TABLE.", ctxEs: "Las indicaciones deben coincidir con los valores de la tabla." },
      { en: "ALERT", es: "Alertar", ctx: "ALERT PERSONNEL TO LEAVE AREA.", ctxEs: "Alerte al personal para que abandone el área." },
      { en: "ALLOW", es: "Permitir", ctx: "DO NOT ALLOW THE CABLE TO TOUCH THE FLOOR.", ctxEs: "No permita que el cable toque el suelo." },
      { en: "ANCHOR", es: "Anclar", ctx: "ANCHOR THE STRAPS TO A FULL-LENGTH RAIL.", ctxEs: "Ancle las correas a un riel de longitud completa." },
      { en: "ANNUNCIATE", es: "Anunciar/Indicar", ctx: "ANNUNCIATE THE FAULT MESSAGE ON THE DISPLAY.", ctxEs: "Indique el mensaje de falla en la pantalla." },
      { en: "ARM", es: "Armar", ctx: "ARM THE AIRCRAFT.", ctxEs: "Arme la aeronave." },
      { en: "ARRANGE", es: "Disponer/Organizar", ctx: "ARRANGE COMPONENTS IN THIS ORDER.", ctxEs: "Organice los componentes en este orden." },
      { en: "ASCERTAIN", es: "Verificar/Asegurar", ctx: "ASCERTAIN THAT THE LIGHT IS OFF.", ctxEs: "Asegúrese de que la luz esté apagada." },
      { en: "ASSIGN", es: "Asignar", ctx: "ASSIGN A CODE TO EACH CONNECTOR.", ctxEs: "Asigne un código a cada conector." },
      { en: "BALANCE", es: "Equilibrar", ctx: "BALANCE THE ELECTRICAL LOADS ON EACH GENERATOR.", ctxEs: "Equilibre las cargas eléctricas en cada generador." },
      { en: "BIND", es: "Atascarse", ctx: "CHECK THAT VALVES DO NOT BIND.", ctxEs: "Verifique que las válvulas no se atasquen." },
      { en: "BLANK", es: "Tapar/Cegar", ctx: "BLANK THE CONNECTOR.", ctxEs: "Tape el conector." },
      { en: "BLOW", es: "Soplar", ctx: "BLOW DRY AIR THROUGH THE FEED AND SPRAY TUBES.", ctxEs: "Sople aire seco a través de los tubos de alimentación y rociado." },
      { en: "BRUSH", es: "Cepillar", ctx: "BRUSH THE FILTER ELEMENT TO CLEAN IT.", ctxEs: "Cepille el elemento filtrante para limpiarlo." },
      { en: "BUILD", es: "Construir/Ensamblar", ctx: "BUILD THE UNIT.", ctxEs: "Ensamble la unidad." },
      { en: "BYPASS", es: "Derivar/Puentear", ctx: "BYPASS THE VALVE.", ctxEs: "Derive la presión hidráulica de la válvula." },
      { en: "CENTER", es: "Centrar", ctx: "CENTER THE PISTON IN THE SLEEVE.", ctxEs: "Centre el pistón en el manguito." }
    ]
  },
  {
    id: 7,
    title: "REPAIR & REPLACEMENT",
    desc: "Repair, replace and restore components",
    color: "#a04000",
    words: [
      { en: "CHARGE", es: "Cargar", ctx: "CHARGE THE BATTERY.", ctxEs: "Cargue la batería." },
      { en: "CHOOSE", es: "Elegir", ctx: "CHOOSE THE HYDRAULIC SYSTEM THAT YOU WILL PRESSURIZE.", ctxEs: "Elija el sistema hidráulico que presurizará." },
      { en: "CIRCULATE", es: "Circular/Hacer circular", ctx: "CIRCULATE AIR AT 24 °C IN THE AREA.", ctxEs: "Haga circular aire a 24 °C en el área." },
      { en: "CLAMP", es: "Sujetar con abrazadera", ctx: "CLAMP ADJOINING CABLES TOGETHER.", ctxEs: "Sujete los cables adyacentes juntos con abrazaderas." },
      { en: "CLEAR", es: "Despejar/Limpiar", ctx: "CLEAR THE DRAIN HOLE.", ctxEs: "Despeje el agujero de drenaje." },
      { en: "COIL", es: "Enrollar", ctx: "COIL THE CABLES CAREFULLY.", ctxEs: "Enrolle los cables cuidadosamente." },
      { en: "COLLAPSE", es: "Colapsar/Plegar", ctx: "COLLAPSE THE BOX.", ctxEs: "Pliegue la caja." },
      { en: "COLLECT", es: "Recolectar/Recoger", ctx: "COLLECT ALL LOOSE ITEMS AND PUT THEM IN THE CONTAINER.", ctxEs: "Recoja todos los objetos sueltos y colóquelos en el contenedor." },
      { en: "COMBINE", es: "Combinar", ctx: "COMBINE WATER AND GLYCOL.", ctxEs: "Combine agua y glicol." },
      { en: "COMMENCE", es: "Comenzar", ctx: "COMMENCE THE TEST AT 2000 RPM.", ctxEs: "Comience la prueba a 2000 RPM." },
      { en: "COMPARE", es: "Comparar", ctx: "COMPARE THE TWO VALUES.", ctxEs: "Compare los dos valores." },
      { en: "COMPLY", es: "Cumplir", ctx: "COMPLY WITH THESE INSTRUCTIONS.", ctxEs: "Cumpla con estas instrucciones." },
      { en: "COMPRESS", es: "Comprimir", ctx: "COMPRESS THE SPRING AND CAREFULLY INSTALL THE COVER.", ctxEs: "Comprima el resorte e instale cuidadosamente la cubierta." },
      { en: "COMPUTE", es: "Computar/Calcular", ctx: "COMPUTE THE VOLTAGE IN THE CIRCUIT.", ctxEs: "Calcule el voltaje en el circuito." },
      { en: "CONDUCT", es: "Realizar/Llevar a cabo", ctx: "CONDUCT THE LEAK TEST.", ctxEs: "Realice la prueba de fugas." },
      { en: "CONFORM", es: "Conformar/Coincidir", ctx: "MAKE SURE THE FLAP EXTENSION CONFORMS TO THE SETTING.", ctxEs: "Asegúrese de que la extensión del flap coincida con la configuración." },
      { en: "CONSIDER", es: "Considerar", ctx: "CONSIDER THE INDICATION BEFORE PROCEEDING.", ctxEs: "Considere la indicación antes de proceder." },
      { en: "CONSIST", es: "Consistir", ctx: "ENSURE THE ASSEMBLY CONSISTS OF THREE PARTS.", ctxEs: "Asegúrese de que el ensamblaje consista en tres partes." }
    ]
  },
  {
    id: 8,
    title: "TESTING & EVALUATION",
    desc: "Test, evaluate and validate systems",
    color: "#2874a6",
    words: [
      { en: "CONSTRUCT", es: "Construir", ctx: "CONSTRUCT THE UNIT.", ctxEs: "Construya la unidad." },
      { en: "CONTAIN", es: "Contener", ctx: "ENSURE THE CONTAINER CONTAINS THE CORRECT ITEMS.", ctxEs: "Asegúrese de que el contenedor contenga los artículos correctos." },
      { en: "CONTROL", es: "Controlar", ctx: "CONTROL THE BUS BAR WITH SWITCH 1.", ctxEs: "Controle la barra colectora con el interruptor 1." },
      { en: "CONVEY", es: "Transportar", ctx: "CONVEY THE EQUIPMENT TO A SAFE AREA.", ctxEs: "Transporte el equipo a un área segura." },
      { en: "CONVERT", es: "Convertir", ctx: "CONVERT THE FUEL LOAD TO U.S. GALLONS.", ctxEs: "Convierta la carga de combustible a galones estadounidenses." },
      { en: "COORDINATE", es: "Coordinar", ctx: "COORDINATE COMPASS SYSTEM 1 AND COMPASS SYSTEM 2.", ctxEs: "Coordine el sistema de brújula 1 y el sistema de brújula 2." },
      { en: "COPY", es: "Copiar", ctx: "COPY THE TAIL NUMBER ON THE RECORD FORM.", ctxEs: "Copie el número de cola en el formulario de registro." },
      { en: "CORRECT", es: "Corregir", ctx: "CORRECT THE TENSION.", ctxEs: "Corrija la tensión." },
      { en: "CORRODE", es: "Corroer", ctx: "THIS MATERIAL CORRODES UNPROTECTED SURFACES.", ctxEs: "Este material corroe las superficies sin protección." },
      { en: "COUPLE", es: "Acoplar", ctx: "COUPLE THE FUELING NOZZLE TO THE AIRCRAFT.", ctxEs: "Acople la boquilla de combustible a la aeronave." },
      { en: "COVER", es: "Cubrir/Abarcar", ctx: "THIS PROCEDURE COVERS REMOVAL OF THE CSD.", ctxEs: "Este procedimiento abarca la remoción del CSD." },
      { en: "CRACK", es: "Agrietarse/Abrirse ligeramente", ctx: "WAIT UNTIL THE RELIEF VALVE CRACKS OPEN.", ctxEs: "Espere hasta que la válvula de alivio se abra ligeramente." },
      { en: "CREATE", es: "Crear", ctx: "CREATE A CLEARANCE BY CUTTING THE BRACKET.", ctxEs: "Cree un espacio libre cortando el soporte." },
      { en: "CROSS", es: "Cruzar", ctx: "DO NOT CROSS THE SAFETY LINE.", ctxEs: "No cruce la línea de seguridad." },
      { en: "CURVE", es: "Curvar", ctx: "CURVE THE STRIP OF METAL.", ctxEs: "Curve la tira de metal." },
      { en: "CYCLE", es: "Ciclar/Operar cíclicamente", ctx: "CYCLE THE ACTUATOR THREE TIMES.", ctxEs: "Opere el actuador tres veces cíclicamente." },
      { en: "DAMAGE", es: "Dañar", ctx: "DO NOT DAMAGE THE ROD.", ctxEs: "No dañe la varilla." },
      { en: "DEACTIVATE", es: "Desactivar", ctx: "DEACTIVATE THE WARNING BELL.", ctxEs: "Desactive la campana de advertencia." }
    ]
  },
  {
    id: 9,
    title: "MOVEMENT & POSITIONING",
    desc: "Move, position and orient components",
    color: "#5d6d7e",
    words: [
      { en: "DEARM", es: "Desarmar", ctx: "DEARM THE ESCAPE SLIDE.", ctxEs: "Desarme el tobogán de escape." },
      { en: "DECELERATE", es: "Desacelerar", ctx: "DECELERATE THE ENGINE TO 500 RPM.", ctxEs: "Desacelere el motor a 500 RPM." },
      { en: "DECREMENT", es: "Decrementar", ctx: "DECREASE THE SETTING IN DECREMENTS OF 60 DEG.", ctxEs: "Disminuya el ajuste en decrementos de 60 grados." },
      { en: "DEDICATE", es: "Dedicar/Usar exclusivamente", ctx: "USE THE DEDICATED TOOL FOR INSTALLATION.", ctxEs: "Use la herramienta dedicada para la instalación." },
      { en: "DE-ENERGIZE", es: "Desenergizar", ctx: "DE-ENERGIZE THE AC AND DC BUSBARS.", ctxEs: "Desenergice las barras colectoras de CA y CC." },
      { en: "DEFUEL", es: "Desabastecer de combustible", ctx: "DEFUEL THE TANK.", ctxEs: "Desabastezca el tanque de combustible." },
      { en: "DEGREASE", es: "Desengrasar", ctx: "DEGREASE THE FAYING SURFACE WITH SOLVENT.", ctxEs: "Desengrase la superficie de unión con solvente." },
      { en: "DE-ICE", es: "Deshielar/Descongelar", ctx: "DE-ICE THE AIRCRAFT.", ctxEs: "Descongele la aeronave." },
      { en: "DELAY", es: "Retrasar", ctx: "DELAY THE USE OF THE STARTER FOR 20 MINUTES.", ctxEs: "Retrase el uso del arrancador durante 20 minutos." },
      { en: "DELETE", es: "Eliminar/Borrar", ctx: "DELETE THE FLIGHT DATA FROM THE TAPE.", ctxEs: "Elimine los datos de vuelo de la cinta." },
      { en: "DEPLOY", es: "Desplegar", ctx: "DEPLOY THE SLIDE RAFT.", ctxEs: "Despliegue el tobogán balsa." },
      { en: "DEPRESS", es: "Presionar", ctx: "DEPRESS AND RELEASE THE BUTTON.", ctxEs: "Presione y suelte el botón." },
      { en: "DEPRESSURIZE", es: "Despresurizar", ctx: "DEPRESSURIZE THE HYDRAULIC SYSTEM.", ctxEs: "Despresurice el sistema hidráulico." },
      { en: "DESCRIBE", es: "Describir", ctx: "THIS SECTION DESCRIBES THE TEST PROCEDURES.", ctxEs: "Esta sección describe los procedimientos de prueba." },
      { en: "DESELECT", es: "Deseleccionar", ctx: "DESELECT THE FREEZE MODE.", ctxEs: "Deseleccione el modo de congelamiento." },
      { en: "DESIGN", es: "Diseñar", ctx: "THE DOORS ARE DESIGNED WITH STEPS FOR ACCESS.", ctxEs: "Las puertas están diseñadas con escalones para el acceso." },
      { en: "DETACH", es: "Desprender/Desconectar", ctx: "DETACH THE PIPELINE FROM THE UNION.", ctxEs: "Desconecte la tubería de la unión." },
      { en: "DETECT", es: "Detectar", ctx: "DETECT DAMAGE TO WIRES BY RUBBING A CLOTH ALONG THEM.", ctxEs: "Detecte daños en los cables frotando un trapo a lo largo de ellos." }
    ]
  },
  {
    id: 10,
    title: "MATERIALS APPLICATION",
    desc: "Apply, cover and treat surfaces",
    color: "#884ea0",
    words: [
      { en: "DETERMINE", es: "Determinar", ctx: "DETERMINE THE DEFECTS IN THE SYSTEM.", ctxEs: "Determine los defectos en el sistema." },
      { en: "DEVIATE", es: "Desviarse", ctx: "DO NOT DEVIATE FROM THIS PROCEDURE.", ctxEs: "No se desvíe de este procedimiento." },
      { en: "DIAGNOSE", es: "Diagnosticar", ctx: "DIAGNOSE THE CAUSE OF THE MALFUNCTION.", ctxEs: "Diagnostique la causa del mal funcionamiento." },
      { en: "DIM", es: "Atenuar", ctx: "DIM THE RETICLE BRIGHTNESS GRADUALLY.", ctxEs: "Atenúe gradualmente el brillo de la retícula." },
      { en: "DIRECT", es: "Dirigir", ctx: "DIRECT THE OPEN END OF THE DRAIN HOSE AWAY FROM THE STRUCTURE.", ctxEs: "Dirija el extremo abierto de la manguera de drenaje lejos de la estructura." },
      { en: "DISASSEMBLE", es: "Desensamblar", ctx: "DISASSEMBLE THE VALVE ASSEMBLY.", ctxEs: "Desensamble el conjunto de la válvula." },
      { en: "DISCARD", es: "Descartar/Desechar", ctx: "REMOVE THE O-RINGS AND DISCARD THEM.", ctxEs: "Retire las juntas tóricas y deséchelas." },
      { en: "DISCHARGE", es: "Descargar/Despresurizar", ctx: "DISCHARGE PRESSURE FROM THE TANKS.", ctxEs: "Descargue la presión de los tanques." },
      { en: "DISCONTINUE", es: "Interrumpir/Suspender", ctx: "DISCONTINUE THE TEST PROCEDURE.", ctxEs: "Suspenda el procedimiento de prueba." },
      { en: "DISENGAGE", es: "Desacoplar", ctx: "DISENGAGE THE CLUTCH BEFORE YOU START THE ENGINE.", ctxEs: "Desacople el embrague antes de arrancar el motor." },
      { en: "DISINFECT", es: "Desinfectar", ctx: "DISINFECT THE MASK ASSEMBLIES.", ctxEs: "Desinfecte los conjuntos de máscaras." },
      { en: "DISMANTLE", es: "Desmantelar", ctx: "DISMANTLE THE BRAKE UNIT IN THE WORKSHOP.", ctxEs: "Desmantele la unidad de freno en el taller." },
      { en: "DISPATCH", es: "Despachar/Enviar", ctx: "DISPATCH THE REPORT TO INSPECTION.", ctxEs: "Despache el informe a inspección." },
      { en: "DISPERSE", es: "Dispersar", ctx: "DISPERSE RESIDUAL FLUID BY BLOWING THROUGH THE TUBES.", ctxEs: "Disperse el fluido residual soplando a través de los tubos." },
      { en: "DISPLACE", es: "Desplazar", ctx: "DISPLACE THE FLUID WITH THE PISTON.", ctxEs: "Desplace el fluido con el pistón." },
      { en: "DISPLAY", es: "Mostrar/Visualizar", ctx: "DISPLAY THE HEADINGS ON THE INDICATORS.", ctxEs: "Muestre los rumbos en los indicadores." },
      { en: "DISPOSE OF", es: "Disponer de/Desechar", ctx: "DISPOSE OF THE USED SOLVENT.", ctxEs: "Deseche el solvente usado." },
      { en: "DISREGARD", es: "Ignorar/No tomar en cuenta", ctx: "DISREGARD STEPS 16 THRU 20.", ctxEs: "No tome en cuenta los pasos 16 al 20." }
    ]
  }
];

export const GROUPS_TMA2: Group[] = [
  {
    id: 11,
    title: "ESTADOS DEL SISTEMA",
    desc: "Reconocer condiciones operativas básicas de componentes",
    color: "#0c6291",
    words: [
      { en: "OPERATIONAL", es: "Operacional", ctx: "MAKE SURE THAT THE SYSTEM IS OPERATIONAL BEFORE FLIGHT.", ctxEs: "Asegúrese de que el sistema esté operacional antes del vuelo." },
      { en: "SERVICEABLE", es: "Serviciable", ctx: "REPLACE THE UNIT IF IT IS NOT SERVICEABLE.", ctxEs: "Reemplace la unidad si no es serviciable." },
      { en: "UNSERVICEABLE", es: "No serviciable", ctx: "DO NOT INSTALL UNSERVICEABLE PARTS.", ctxEs: "No instale partes no serviciables." },
      { en: "INOPERATIVE", es: "Inoperativo", ctx: "THE SYSTEM IS INOPERATIVE UNTIL THE REPAIR IS COMPLETED.", ctxEs: "El sistema está inoperativo hasta que se complete la reparación." },
      { en: "ACTIVE", es: "Activo", ctx: "MAKE SURE THAT THE WARNING LIGHT IS ACTIVE.", ctxEs: "Asegúrese de que la luz de advertencia esté activa." },
      { en: "INACTIVE", es: "Inactivo", ctx: "THE SENSOR IS INACTIVE WHEN THE POWER IS OFF.", ctxEs: "El sensor está inactivo cuando la energía está apagada." },
      { en: "ARMED", es: "Armado", ctx: "SET THE SWITCH TO THE ARMED POSITION.", ctxEs: "Ajuste el interruptor a la posición armado." },
      { en: "DISARMED", es: "Desarmado", ctx: "DISARM THE SYSTEM BEFORE MAINTENANCE.", ctxEs: "Desarme el sistema antes del mantenimiento." },
      { en: "NORMAL", es: "Normal", ctx: "OPERATE THE SYSTEM IN NORMAL MODE.", ctxEs: "Opere el sistema en modo normal." },
      { en: "ABNORMAL", es: "Anormal", ctx: "IF YOU GET ABNORMAL INDICATIONS, DO A SYSTEM TEST.", ctxEs: "Si obtiene indicaciones anormales, haga una prueba del sistema." },
      { en: "STANDBY", es: "En espera", ctx: "SET THE SYSTEM TO STANDBY MODE.", ctxEs: "Ajuste el sistema a modo en espera." },
      { en: "EMERGENCY", es: "Emergencia", ctx: "IN AN EMERGENCY, OPERATE THE MANUAL OVERRIDE.", ctxEs: "En una emergencia, opere la anulación manual." },
      { en: "READY", es: "Listo", ctx: "MAKE SURE THAT THE UNIT IS READY FOR OPERATION.", ctxEs: "Asegúrese de que la unidad esté lista para operación." },
      { en: "AVAILABLE", es: "Disponible", ctx: "IF ELECTRICAL POWER IS AVAILABLE, DO THE TEST.", ctxEs: "Si la energía eléctrica está disponible, haga la prueba." },
      { en: "ENABLED", es: "Habilitado", ctx: "THE FUNCTION IS ENABLED WHEN THE SWITCH IS ON.", ctxEs: "La función está habilitada cuando el interruptor está encendido." },
      { en: "DISABLED", es: "Deshabilitado", ctx: "THE WARNING IS DISABLED DURING MAINTENANCE.", ctxEs: "La advertencia está deshabilitada durante el mantenimiento." },
      { en: "CONNECTED", es: "Conectado", ctx: "MAKE SURE THAT THE CABLE IS CONNECTED.", ctxEs: "Asegúrese de que el cable esté conectado." },
      { en: "DISCONNECTED", es: "Desconectado", ctx: "DO NOT OPERATE THE SYSTEM WHEN THE CABLE IS DISCONNECTED.", ctxEs: "No opere el sistema cuando el cable esté desconectado." },
      { en: "ENGAGED", es: "Acoplado", ctx: "MAKE SURE THAT THE CLUTCH IS ENGAGED.", ctxEs: "Asegúrese de que el embrague esté acoplado." },
      { en: "DISENGAGED", es: "Desacoplado", ctx: "DISENGAGE THE CLUTCH BEFORE REMOVAL.", ctxEs: "Desacople el embrague antes de la remoción." },
      { en: "LOCKED", es: "Bloqueado", ctx: "LOCK THE SWITCH AND REMOVE THE KEY.", ctxEs: "Bloquee el interruptor y retire la llave." },
      { en: "UNLOCKED", es: "Desbloqueado", ctx: "MAKE SURE THAT THE DOOR IS UNLOCKED.", ctxEs: "Asegúrese de que la puerta esté desbloqueada." },
      { en: "OPEN", es: "Abierto", ctx: "OPEN THE VALVE TO START THE FLOW.", ctxEs: "Abra la válvula para iniciar el flujo." },
      { en: "CLOSED", es: "Cerrado", ctx: "MAKE SURE THAT THE DOOR IS CLOSED.", ctxEs: "Asegúrese de que la puerta esté cerrada." },
      { en: "SEALED", es: "Sellado", ctx: "MAKE SURE THAT THE CONTAINER IS SEALED.", ctxEs: "Asegúrese de que el contenedor esté sellado." },
      { en: "UNSEALED", es: "No sellado", ctx: "DO NOT USE UNSEALED CONTAINERS.", ctxEs: "No use contenedores no sellados." },
      { en: "PRESSURIZED", es: "Presurizado", ctx: "MAKE SURE THAT THE SYSTEM IS NOT PRESSURIZED.", ctxEs: "Asegúrese de que el sistema no esté presurizado." },
      { en: "DEPRESSURIZED", es: "Despresurizado", ctx: "DEPRESSURIZE THE SYSTEM BEFORE REMOVAL.", ctxEs: "Despresurice el sistema antes de la remoción." },
      { en: "ENERGIZED", es: "Energizado", ctx: "DO NOT TOUCH ENERGIZED COMPONENTS.", ctxEs: "No toque componentes energizados." },
      { en: "DE-ENERGIZED", es: "Desenergizado", ctx: "DE-ENERGIZE THE SYSTEM BEFORE MAINTENANCE.", ctxEs: "Desenergice el sistema antes del mantenimiento." }
    ]
  },
  {
    id: 12,
    title: "CONDICIONES DE FALLA",
    desc: "Identificar y describir defectos y daños técnicos",
    color: "#a94a42",
    words: [
      { en: "FAULT", es: "Falla", ctx: "IF THERE IS A FAULT, DO THE TROUBLESHOOTING PROCEDURE.", ctxEs: "Si hay una falla, haga el procedimiento de localización de fallas." },
      { en: "FAILURE", es: "Fallo", ctx: "IF FAILURE OCCURS, STOP THE TEST.", ctxEs: "Si ocurre un fallo, detenga la prueba." },
      { en: "MALFUNCTION", es: "Mal funcionamiento", ctx: "IF A MALFUNCTION OCCURS, REFER TO THE MANUAL.", ctxEs: "Si ocurre un mal funcionamiento, refiérase al manual." },
      { en: "DEFECT", es: "Defecto", ctx: "EXAMINE THE PART FOR DEFECTS.", ctxEs: "Examine la parte en busca de defectos." },
      { en: "DAMAGE", es: "Daño", ctx: "EXAMINE THE AREA FOR DAMAGE.", ctxEs: "Examine el área en busca de daño." },
      { en: "DAMAGED", es: "Dañado", ctx: "REPLACE DAMAGED PARTS.", ctxEs: "Reemplace las partes dañadas." },
      { en: "WORN", es: "Desgastado", ctx: "REPLACE WORN COMPONENTS.", ctxEs: "Reemplace los componentes desgastados." },
      { en: "WEAR", es: "Desgaste", ctx: "EXAMINE THE BEARING FOR WEAR.", ctxEs: "Examine el cojinete en busca de desgaste." },
      { en: "CORROSION", es: "Corrosión", ctx: "REMOVE CORROSION WITH THE SPECIFIED MATERIAL.", ctxEs: "Retire la corrosión con el material especificado." },
      { en: "CORRODED", es: "Corroído", ctx: "REPLACE CORRODED FASTENERS.", ctxEs: "Reemplace los sujetadores corroídos." },
      { en: "CRACK", es: "Grieta", ctx: "EXAMINE THE SURFACE FOR CRACKS.", ctxEs: "Examine la superficie en busca de grietas." },
      { en: "CRACKED", es: "Agrietado", ctx: "REPLACE CRACKED COMPONENTS.", ctxEs: "Reemplace los componentes agrietados." },
      { en: "LEAK", es: "Fuga", ctx: "EXAMINE THE SYSTEM FOR LEAKS.", ctxEs: "Examine el sistema en busca de fugas." },
      { en: "LEAKING", es: "Con fuga", ctx: "IF THE VALVE IS LEAKING, REPLACE IT.", ctxEs: "Si la válvula tiene fuga, reemplácela." },
      { en: "BLOCKAGE", es: "Obstrucción", ctx: "REMOVE THE BLOCKAGE FROM THE TUBE.", ctxEs: "Retire la obstrucción del tubo." },
      { en: "BLOCKED", es: "Obstruido", ctx: "IF THE FILTER IS BLOCKED, REPLACE IT.", ctxEs: "Si el filtro está obstruido, reemplácelo." },
      { en: "CLOGGED", es: "Taponado", ctx: "CLEAN CLOGGED DRAIN HOLES.", ctxEs: "Limpie los agujeros de drenaje taponados." },
      { en: "CONTAMINATED", es: "Contaminado", ctx: "DO NOT USE CONTAMINATED FLUID.", ctxEs: "No use fluido contaminado." },
      { en: "CONTAMINATION", es: "Contaminación", ctx: "REMOVE CONTAMINATION FROM THE SYSTEM.", ctxEs: "Retire la contaminación del sistema." },
      { en: "DIRTY", es: "Sucio", ctx: "CLEAN DIRTY COMPONENTS.", ctxEs: "Limpie los componentes sucios." },
      { en: "CLEAN", es: "Limpio", ctx: "MAKE SURE THAT THE SURFACE IS CLEAN.", ctxEs: "Asegúrese de que la superficie esté limpia." }
    ]
  },
  {
    id: 13,
    title: "CONDICIONES AMBIENTALES",
    desc: "Comprender factores externos que afectan la operación",
    color: "#4a69bd",
    words: [
      { en: "TEMPERATURE", es: "Temperatura", ctx: "MEASURE THE TEMPERATURE OF THE OIL.", ctxEs: "Mida la temperatura del aceite." },
      { en: "PRESSURE", es: "Presión", ctx: "MEASURE THE PRESSURE IN THE SYSTEM.", ctxEs: "Mida la presión en el sistema." },
      { en: "HUMIDITY", es: "Humedad", ctx: "HIGH HUMIDITY CAN CAUSE CORROSION.", ctxEs: "La alta humedad puede causar corrosión." },
      { en: "VIBRATION", es: "Vibración", ctx: "EXAMINE THE MOUNTING FOR VIBRATION DAMAGE.", ctxEs: "Examine el montaje en busca de daño por vibración." },
      { en: "WIND", es: "Viento", ctx: "DO NOT OPEN DOORS IN STRONG WIND.", ctxEs: "No abra puertas con viento fuerte." },
      { en: "RAIN", es: "Lluvia", ctx: "PROTECT THE UNIT FROM RAIN.", ctxEs: "Proteja la unidad de la lluvia." },
      { en: "ICE", es: "Hielo", ctx: "REMOVE ICE FROM THE WING.", ctxEs: "Retire el hielo del ala." },
      { en: "SNOW", es: "Nieve", ctx: "REMOVE SNOW FROM THE AIRCRAFT.", ctxEs: "Retire la nieve de la aeronave." },
      { en: "TURBULENCE", es: "Turbulencia", ctx: "TURBULENCE CAN CAUSE UNWANTED MOVEMENT.", ctxEs: "La turbulencia puede causar movimiento no deseado." },
      { en: "LIGHTNING", es: "Rayo", ctx: "AVOID MAINTENANCE DURING LIGHTNING.", ctxEs: "Evite el mantenimiento durante rayos." },
      { en: "HOT", es: "Caliente", ctx: "DO NOT TOUCH HOT SURFACES.", ctxEs: "No toque superficies calientes." },
      { en: "COLD", es: "Frío", ctx: "PROTECT COMPONENTS FROM COLD TEMPERATURES.", ctxEs: "Proteja los componentes de temperaturas frías." },
      { en: "WARM", es: "Cálido", ctx: "LET THE COMPONENT BECOME WARM BEFORE OPERATION.", ctxEs: "Deje que el componente se vuelva cálido antes de la operación." },
      { en: "COOL", es: "Enfriar", ctx: "LET THE ENGINE COOL BEFORE REMOVAL.", ctxEs: "Deje que el motor se enfríe antes de la remoción." },
      { en: "DRY", es: "Seco", ctx: "MAKE SURE THAT THE SURFACE IS DRY.", ctxEs: "Asegúrese de que la superficie esté seca." },
      { en: "WET", es: "Húmedo", ctx: "DO NOT OPERATE WITH WET COMPONENTS.", ctxEs: "No opere con componentes húmedos." },
      { en: "MOIST", es: "Humedad", ctx: "REMOVE MOISTURE FROM THE SYSTEM.", ctxEs: "Retire la humedad del sistema." }
    ]
  },
  {
    id: 14,
    title: "NIVELES Y LÍMITES",
    desc: "Interpretar valores, rangos y tolerancias técnicas",
    color: "#6c5ce7",
    words: [
      { en: "MINIMUM", es: "Mínimo", ctx: "THE MINIMUM PRESSURE IS 3000 PSI.", ctxEs: "La presión mínima es 3000 PSI." },
      { en: "MAXIMUM", es: "Máximo", ctx: "DO NOT EXCEED THE MAXIMUM PRESSURE.", ctxEs: "No exceda la presión máxima." },
      { en: "LIMIT", es: "Límite", ctx: "MAKE SURE THAT THE VALUES ARE IN THE LIMITS.", ctxEs: "Asegúrese de que los valores estén en los límites." },
      { en: "THRESHOLD", es: "Umbral", ctx: "THE WARNING OPERATES AT THE THRESHOLD VALUE.", ctxEs: "La advertencia opera en el valor umbral." },
      { en: "RANGE", es: "Rango", ctx: "MAKE SURE THAT THE INDICATION IS IN THE RANGE.", ctxEs: "Asegúrese de que la indicación esté en el rango." },
      { en: "TOLERANCE", es: "Tolerancia", ctx: "THE TOLERANCE IS PLUS OR MINUS 0.1 mm.", ctxEs: "La tolerancia es más o menos 0.1 mm." },
      { en: "CLEARANCE", es: "Holgura", ctx: "MEASURE THE CLEARANCE BETWEEN THE PARTS.", ctxEs: "Mida la holgura entre las partes." },
      { en: "GAP", es: "Espacio", ctx: "MEASURE THE GAP WITH FEELER GAUGES.", ctxEs: "Mida el espacio con calibradores de láminas." },
      { en: "MARGIN", es: "Margen", ctx: "THE SAFETY MARGIN IS 10 PERCENT.", ctxEs: "El margen de seguridad es 10 por ciento." },
      { en: "EXCESS", es: "Exceso", ctx: "REMOVE EXCESS SEALANT.", ctxEs: "Retire el exceso de sellador." },
      { en: "INSUFFICIENT", es: "Insuficiente", ctx: "IF THE PRESSURE IS INSUFFICIENT, CHECK THE PUMP.", ctxEs: "Si la presión es insuficiente, verifique la bomba." },
      { en: "SUFFICIENT", es: "Suficiente", ctx: "MAKE SURE THAT THERE IS SUFFICIENT FLUID.", ctxEs: "Asegúrese de que haya fluido suficiente." }
    ]
  },
  {
    id: 15,
    title: "DIRECCIONES Y POSICIONES",
    desc: "Ubicar componentes y describir orientaciones espaciales",
    color: "#12cbc4",
    words: [
      { en: "FORWARD", es: "Delantero", ctx: "THE PUMP IS INSTALLED IN THE FORWARD SECTION.", ctxEs: "La bomba está instalada en la sección delantera." },
      { en: "AFT", es: "Trasero", ctx: "THE UNIT IS INSTALLED IN THE AFT CARGO COMPARTMENT.", ctxEs: "La unidad está instalada en el compartimento de carga trasero." },
      { en: "INBOARD", es: "Interior", ctx: "REMOVE THE INBOARD FAIRING.", ctxEs: "Retire el carenado interior." },
      { en: "OUTBOARD", es: "Exterior", ctx: "REMOVE THE OUTBOARD FAIRING.", ctxEs: "Retire el carenado exterior." },
      { en: "UPPER", es: "Superior", ctx: "EXAMINE THE UPPER SURFACE.", ctxEs: "Examine la superficie superior." },
      { en: "LOWER", es: "Inferior", ctx: "EXAMINE THE LOWER SURFACE.", ctxEs: "Examine la superficie inferior." },
      { en: "LEFT", es: "Izquierdo", ctx: "THE SENSOR IS ON THE LEFT SIDE.", ctxEs: "El sensor está en el lado izquierdo." },
      { en: "RIGHT", es: "Derecho", ctx: "THE SENSOR IS ON THE RIGHT SIDE.", ctxEs: "El sensor está en el lado derecho." },
      { en: "CENTER", es: "Centro", ctx: "THE INDICATOR IS IN THE CENTER OF THE PANEL.", ctxEs: "El indicador está en el centro del panel." },
      { en: "LATERAL", es: "Lateral", ctx: "ADJUST THE LATERAL TRIM.", ctxEs: "Ajuste el trim lateral." },
      { en: "LONGITUDINAL", es: "Longitudinal", ctx: "ADJUST THE LONGITUDINAL TRIM.", ctxEs: "Ajuste el trim longitudinal." },
      { en: "VERTICAL", es: "Vertical", ctx: "MEASURE THE VERTICAL DISTANCE.", ctxEs: "Mida la distancia vertical." },
      { en: "HORIZONTAL", es: "Horizontal", ctx: "MAKE SURE THAT THE SURFACE IS HORIZONTAL.", ctxEs: "Asegúrese de que la superficie esté horizontal." },
      { en: "PARALLEL", es: "Paralelo", ctx: "MAKE SURE THAT THE RODS ARE PARALLEL.", ctxEs: "Asegúrese de que las varillas estén paralelas." },
      { en: "PERPENDICULAR", es: "Perpendicular", ctx: "MAKE SURE THAT THE TOOL IS PERPENDICULAR.", ctxEs: "Asegúrese de que la herramienta esté perpendicular." },
      { en: "ALIGNED", es: "Alineado", ctx: "MAKE SURE THAT THE HOLES ARE ALIGNED.", ctxEs: "Asegúrese de que los agujeros estén alineados." },
      { en: "MISALIGNED", es: "Desalineado", ctx: "IF THE PARTS ARE MISALIGNED, ADJUST THEM.", ctxEs: "Si las partes están desalineadas, ajústelas." }
    ]
  },
  {
    id: 16,
    title: "ESTADOS DE CALIDAD",
    desc: "Evaluar condiciones físicas y de seguridad",
    color: "#ff8200",
    words: [
      { en: "LEVEL", es: "Nivelado", ctx: "MAKE THE AIRCRAFT LEVEL.", ctxEs: "Nivele la aeronave." },
      { en: "UNLEVEL", es: "Desnivelado", ctx: "DO NOT JACK THE AIRCRAFT ON UNLEVEL GROUND.", ctxEs: "No levante la aeronave en terreno desnivelado." },
      { en: "STABLE", es: "Estable", ctx: "MAKE SURE THAT THE INDICATIONS ARE STABLE.", ctxEs: "Asegúrese de que las indicaciones estén estables." },
      { en: "UNSTABLE", es: "Inestable", ctx: "IF THE INDICATIONS ARE UNSTABLE, DO A TEST.", ctxEs: "Si las indicaciones son inestables, haga una prueba." },
      { en: "CONSTANT", es: "Constante", ctx: "MAKE SURE THAT THE PRESSURE IS CONSTANT.", ctxEs: "Asegúrese de que la presión sea constante." },
      { en: "VARIABLE", es: "Variable", ctx: "THE TEMPERATURE IS VARIABLE.", ctxEs: "La temperatura es variable." },
      { en: "CONTINUOUS", es: "Continuo", ctx: "THE FLOW MUST BE CONTINUOUS.", ctxEs: "El flujo debe ser continuo." },
      { en: "INTERMITTENT", es: "Intermitente", ctx: "IF THE FLOW IS INTERMITTENT, CHECK THE VALVE.", ctxEs: "Si el flujo es intermitente, verifique la válvula." },
      { en: "SMOOTH", es: "Suave", ctx: "MAKE SURE THAT THE MOVEMENT IS SMOOTH.", ctxEs: "Asegúrese de que el movimiento sea suave." },
      { en: "ROUGH", es: "Rugoso", ctx: "IF THE SURFACE IS ROUGH, POLISH IT.", ctxEs: "Si la superficie es rugosa, púlala." },
      { en: "FLAT", es: "Plano", ctx: "MAKE SURE THAT THE SURFACE IS FLAT.", ctxEs: "Asegúrese de que la superficie esté plana." },
      { en: "CURVED", es: "Curvo", ctx: "THE PATCH MUST BE CURVED.", ctxEs: "El parche debe ser curvo." },
      { en: "STRAIGHT", es: "Recto", ctx: "MAKE THE ROD STRAIGHT.", ctxEs: "Enderece la varilla." },
      { en: "TIGHT", es: "Apretado", ctx: "MAKE SURE THAT THE BOLTS ARE TIGHT.", ctxEs: "Asegúrese de que los tornillos estén apretados." },
      { en: "LOOSE", es: "Suelto", ctx: "TIGHTEN LOOSE FASTENERS.", ctxEs: "Apriete los sujetadores sueltos." },
      { en: "SECURE", es: "Asegurado", ctx: "MAKE SURE THAT THE COMPONENT IS SECURE.", ctxEs: "Asegúrese de que el componente esté asegurado." },
      { en: "UNSAFE", es: "Inseguro", ctx: "DO NOT WORK IN UNSAFE CONDITIONS.", ctxEs: "No trabaje en condiciones inseguras." },
      { en: "SAFE", es: "Seguro", ctx: "MAKE THE AREA SAFE BEFORE WORK.", ctxEs: "Haga el área segura antes de trabajar." },
      { en: "CLEAR", es: "Despejado", ctx: "MAKE SURE THAT THE AREA IS CLEAR.", ctxEs: "Asegúrese de que el area esté despejada." },
      { en: "OBSTRUCTED", es: "Obstruido", ctx: "REMOVE OBSTRUCTED ITEMS.", ctxEs: "Retire los elementos obstruidos." },
      { en: "UNOBSTRUCTED", es: "Sin obstrucción", ctx: "MAKE SURE THAT THE VIEW IS UNOBSTRUCTED.", ctxEs: "Asegúrese de que la vista esté sin obstrucción." },
      { en: "VISIBLE", es: "Visible", ctx: "MAKE SURE THAT THE MARK IS VISIBLE.", ctxEs: "Asegúrese de que la marca sea visible." },
      { en: "HIDDEN", es: "Oculto", ctx: "DO NOT INSTALL HIDDEN COMPONENTS.", ctxEs: "No instale componentes ocultos." }
    ]
  }
];

export const GROUPS_TMA3: Group[] = [
  {
    id: 17,
    title: "ETIQUETAS DE ADVERTENCIA",
    desc: "Identificar niveles de riesgo y señales de seguridad",
    color: "#eb2f06",
    words: [
      { en: "WARNING", es: "Advertencia", ctx: "WARNING: HIGH VOLTAGE CAN CAUSE INJURY OR DEATH.", ctxEs: "ADVERTENCIA: EL ALTO VOLTAJE PUEDE CAUSAR LESIONES O MUERTE." },
      { en: "CAUTION", es: "Precaución", ctx: "CAUTION: HOT SURFACES CAN CAUSE BURNS.", ctxEs: "PRECAUCIÓN: LAS SUPERFICIES CALIENTES PUEDEN CAUSAR QUEMADURAS." },
      { en: "NOTE", es: "Nota", ctx: "NOTE: THIS STEP IS NOT MANDATORY.", ctxEs: "NOTA: ESTE PASO NO ES OBLIGATORIO." },
      { en: "DANGER", es: "Peligro", ctx: "DANGER: EXPLOSIVE MATERIAL. KEEP AWAY FROM FLAMES.", ctxEs: "PELIGRO: MATERIAL EXPLOSIVO. MANTÉNGASE ALEJADO DE LLAMAS." },
      { en: "ATTENTION", es: "Atención", ctx: "ATTENTION: READ ALL INSTRUCTIONS BEFORE START.", ctxEs: "ATENCIÓN: LEA TODAS LAS INSTRUCCIONES ANTES DE INICIAR." },
      { en: "NOTICE", es: "Aviso", ctx: "NOTICE: EQUIPMENT DAMAGE POSSIBLE IF PROCEDURE NOT FOLLOWED.", ctxEs: "AVISO: DAÑO AL EQUIPOS POSIBLE SI NO SE SIGUE EL PROCEDIMIENTO." },
      { en: "HAZARD", es: "Riesgo", ctx: "HAZARD: ELECTRICAL SHOCK RISK IN THIS AREA.", ctxEs: "RIESGO: RIESGO DE DESCARGA ELÉCTRICA EN ESTA ÁREA." },
      { en: "RISK", es: "Riesgo", ctx: "RISK OF FIRE IF FLAMMABLE MATERIAL IS NEAR HEAT SOURCE.", ctxEs: "RIESGO DE INCENDIO SI MATERIAL INFLAMABLE ESTÁ CERCA DE FUENTE DE CALOR." },
      { en: "SAFE", es: "Seguro", ctx: "MAKE THE AREA SAFE BEFORE YOU START WORK.", ctxEs: "HAGA EL ÁREA SEGURA ANTES DE INICIAR EL TRABAJO." },
      { en: "UNSAFE", es: "Inseguro", ctx: "DO NOT WORK IN UNSAFE CONDITIONS.", ctxEs: "NO TRABAJE EN CONDICIONES INSEGURAS." }
    ]
  },
  {
    id: 18,
    title: "EQUIPO DE PROTECCIÓN PERSONAL",
    desc: "Reconocer y usar correctamente el EPP",
    color: "#0a3d62",
    words: [
      { en: "PROTECTIVE", es: "Protector", ctx: "PUT ON PROTECTIVE CLOTHING BEFORE YOU ENTER THE AREA.", ctxEs: "PONGA ROPA PROTECTORA ANTES DE ENTRAR AL ÁREA." },
      { en: "GOGGLES", es: "Gafas", ctx: "USE SAFETY GOGGLES WHEN YOU WORK WITH CHEMICALS.", ctxEs: "USE GAFAS DE SEGURIDAD CUANDO TRABAJE CON QUÍMICOS." },
      { en: "GLOVES", es: "Guantes", ctx: "PUT ON PROTECTIVE GLOVES TO PREVENT SKIN CONTACT.", ctxEs: "PONGA GUANTES PROTECTORES PARA PREVENIR CONTACTO CON LA PIEL." },
      { en: "HELMET", es: "Casco", ctx: "WEAR A HELMET WHEN YOU WORK NEAR MOVING PARTS.", ctxEs: "USE UN CASCO CUANDO TRABAJE CERCA DE PARTES MÓVILES." },
      { en: "MASK", es: "Máscara", ctx: "PUT ON A RESPIRATOR MASK IF AIR QUALITY IS POOR.", ctxEs: "PONGA UNA MÁSCARA RESPIRADORA SI LA CALIDAD DEL AIRE ES POBRE." },
      { en: "HARNESS", es: "Arnés", ctx: "ATTACH THE SAFETY HARNESS BEFORE YOU CLIMB.", ctxEs: "AJUSTE EL ARNÉS DE SEGURIDAD ANTES DE ESCALAR." },
      { en: "VEST", es: "Chaleco", ctx: "WEAR A HIGH-VISIBILITY VEST IN THE WORK AREA.", ctxEs: "USE UN CHALECO DE ALTA VISIBILIDAD EN EL ÁREA DE TRABAJO." },
      { en: "FOOTWEAR", es: "Calzado", ctx: "USE PROTECTIVE FOOTWEAR TO PREVENT INJURY.", ctxEs: "USE CALZADO PROTECTOR PARA PREVENIR LESIONES." },
      { en: "CLOTHING", es: "Ropa", ctx: "REMOVE LOOSE CLOTHING BEFORE YOU OPERATE MACHINERY.", ctxEs: "RETIRE LA ROPA SUELTA ANTES DE OPERAR MAQUINARIA." },
      { en: "EAR PROTECTION", es: "Protección auditiva", ctx: "USE EAR PROTECTION WHEN NOISE LEVEL IS HIGH.", ctxEs: "USE PROTECCIÓN AUDITIVA CUANDO EL NIVEL DE RUIDO ES ALTO." }
    ]
  },
  {
    id: 19,
    title: "PROCEDIMIENTOS DE EMERGENCIA",
    desc: "Ejecutar acciones correctas en situaciones críticas",
    color: "#d63031",
    words: [
      { en: "EMERGENCY", es: "Emergencia", ctx: "IN AN EMERGENCY, PUSH THE RED BUTTON TO STOP THE SYSTEM.", ctxEs: "EN UNA EMERGENCIA, PRESIONE EL BOTÓN ROJO PARA DETENER EL SISTEMA." },
      { en: "EVACUATE", es: "Evacuar", ctx: "EVACUATE THE AREA IMMEDIATELY IF YOU HEAR THE ALARM.", ctxEs: "EVACÚE EL ÁREA INMEDIATAMENTE SI ESCUCHA LA ALARMA." },
      { en: "EXTINGUISH", es: "Extinguir", ctx: "USE A FIRE EXTINGUISHER TO EXTINGUISH SMALL FIRES.", ctxEs: "USE UN EXTINTOR PARA EXTINGUIR INCENDIOS PEQUEÑOS." },
      { en: "SHUTOFF", es: "Cierre de emergencia", ctx: "OPERATE THE EMERGENCY SHUTOFF VALVE TO STOP FUEL FLOW.", ctxEs: "OPERE LA VÁLVULA DE CIERRE DE EMERGENCIA PARA DETENER EL FLUJO DE COMBUSTIBLE." },
      { en: "CRASH SWITCH", es: "Interruptor de emergencia", ctx: "PUSH THE CRASH SWITCH TO ISOLATE ELECTRICAL POWER.", ctxEs: "PRESIONE EL INTERRUPTOR DE EMERGENCIA PARA AISLAR LA ENERGÍA ELÉCTRICA." },
      { en: "FIRST AID", es: "Primeros auxilios", ctx: "GET FIRST AID IMMEDIATELY IF YOU GET CHEMICAL ON YOUR SKIN.", ctxEs: "OBTENGA PRIMEROS AUXILIOS INMEDIATAMENTE SI RECIBE QUÍMICO EN LA PIEL." },
      { en: "MEDICAL AID", es: "Ayuda médica", ctx: "GET MEDICAL AID IF YOU BREATHE SOLVENT FUMES.", ctxEs: "OBTENGA AYUDA MÉDICA SI RESPIRA VAPORES DE SOLVENTE." },
      { en: "ALARM", es: "Alarma", ctx: "WHEN THE ALARM OPERATES, STOP ALL WORK IMMEDIATELY.", ctxEs: "CUANDO LA ALARMA OPERE, DETENGA TODO TRABAJO INMEDIATAMENTE." },
      { en: "EXIT", es: "Salida", ctx: "USE THE NEAREST EMERGENCY EXIT TO LEAVE THE AREA.", ctxEs: "USE LA SALIDA DE EMERGENCIA MÁS CERCANA PARA SALIR DEL ÁREA." },
      { en: "ASSEMBLY POINT", es: "Punto de reunión", ctx: "GO TO THE ASSEMBLY POINT AFTER YOU EVACUATE.", ctxEs: "VAYA AL PUNTO DE REUNIÓN DESPUÉS DE EVACUAR." }
    ]
  },
  {
    id: 20,
    title: "TIPOS DE PELIGROS",
    desc: "Identificar y clasificar riesgos específicos",
    color: "#e67e22",
    words: [
      { en: "FIRE", es: "Incendio", ctx: "IF THERE IS A FIRE, OPERATE THE FIRE SHUTOFF VALVE.", ctxEs: "SI HAY UN INCENDIO, OPERE LA VÁLVULA DE CIERRE DE INCENDIO." },
      { en: "EXPLOSION", es: "Explosión", ctx: "OXYGEN AND OIL MAKE AN EXPLOSIVE MIXTURE.", ctxEs: "EL OXÍGENO Y EL ACEITE HACEN UNA MEZCLA EXPLOSIVA." },
      { en: "ELECTRICAL SHOCK", es: "Descarga eléctrica", ctx: "HIGH VOLTAGE CAN CAUSE ELECTRICAL SHOCK.", ctxEs: "EL ALTO VOLTAJE PUEDE CAUSAR DESCARGA ELÉCTRICA." },
      { en: "HIGH PRESSURE", es: "Alta presión", ctx: "HIGH PRESSURE CAN CAUSE INJURY IF A LINE BREAKS.", ctxEs: "LA ALTA PRESIÓN PUEDE CAUSAR LESIÓN SI UNA LÍNEA SE ROMPE." },
      { en: "HIGH TEMPERATURE", es: "Alta temperatura", ctx: "HOT SURFACES CAN CAUSE BURNS. TOUCH WITH CARE.", ctxEs: "LAS SUPERFICIES CALIENTES PUEDEN CAUSAR QUEMADURAS. TOQUE CON CUIDADO." },
      { en: "TOXIC", es: "Tóxico", ctx: "THIS MATERIAL IS TOXIC. DO NOT BREATHE THE FUMES.", ctxEs: "ESTE MATERIAL ES TÓXICO. NO RESPIRE LOS VAPORES." },
      { en: "FLAMMABLE", es: "Inflamable", ctx: "SOLVENT IS FLAMMABLE. KEEP AWAY FROM FLAMES.", ctxEs: "EL SOLVENTE ES INFLAMABLE. MANTÉNGALO ALEJADO DE LLAMAS." },
      { en: "CORROSIVE", es: "Corrosivo", ctx: "ACID IS CORROSIVE. USE PROTECTIVE GLOVES.", ctxEs: "EL ÁCIDO ES CORROSIVO. USE GUANTES PROTECTORES." },
      { en: "SHARP EDGES", es: "Bordes afilados", ctx: "BE CAREFUL OF SHARP EDGES. THEY CAN CAUSE CUTS.", ctxEs: "TENGA CUIDADO CON BORDES AFILADOS. PUEDEN CAUSAR CORTES." },
      { en: "MOVING PARTS", es: "Partes móviles", ctx: "KEEP HANDS AWAY FROM MOVING PARTS.", ctxEs: "MANTENGA LAS MANOS ALEJADAS DE PARTES MÓVILES." }
    ]
  },
  {
    id: 21,
    title: "ACCIONES DE SEGURIDAD",
    desc: "Aplicar comandos preventivos y correctivos",
    color: "#16a085",
    words: [
      { en: "ISOLATE", es: "Aislar", ctx: "ISOLATE ELECTRICAL POWER BEFORE YOU START WORK.", ctxEs: "AÍSLE LA ENERGÍA ELÉCTRICA ANTES DE INICIAR EL TRABAJO." },
      { en: "DE-ENERGIZE", es: "Desenergizar", ctx: "DE-ENERGIZE THE SYSTEM BEFORE YOU REMOVE COMPONENTS.", ctxEs: "DESENERGICE EL SISTEMA ANTES DE RETIRAR COMPONENTES." },
      { en: "LOCK", es: "Bloquear", ctx: "LOCK THE SWITCH AND REMOVE THE KEY TO PREVENT OPERATION.", ctxEs: "BLOQUEE EL INTERRUPTOR Y RETIRE LA LLAVE PARA PREVENIR OPERACIÓN." },
      { en: "TAG", es: "Etiquetar", ctx: "TAG THE CIRCUIT BREAKER WITH \"DO NOT OPERATE\".", ctxEs: "ETIQUETE EL INTERRUPTOR AUTOMÁTICO CON \"NO OPERAR\"." },
      { en: "SAFETY", es: "Asegurar", ctx: "SAFETY THE VALVE WITH A LOCKING PIN BEFORE REMOVAL.", ctxEs: "ASEGURE LA VÁLVULA CON UN PASADOR DE BLOQUEO ANTES DE LA REMOCIÓN." },
      { en: "PREVENT", es: "Prevenir", ctx: "PREVENT INJURY BY USING THE CORRECT TOOLS.", ctxEs: "PREVENGA LESIONES USANDO LAS HERRAMIENTAS CORRECTAS." },
      { en: "AVOID", es: "Evitar", ctx: "AVOID CONTACT WITH HOT SURFACES.", ctxEs: "EVITE CONTACTO CON SUPERFICIES CALIENTES." },
      { en: "KEEP AWAY", es: "Mantener alejado", ctx: "KEEP PERSONNEL AWAY FROM THE ENGINE EXHAUST.", ctxEs: "MANTENGA AL PERSONAL ALEJADO DEL ESCAPE DEL MOTOR." },
      { en: "DO NOT", es: "No", ctx: "DO NOT OPERATE THE SYSTEM WITHOUT APPROVAL.", ctxEs: "NO OPERE EL SISTEMA SIN APROBACIÓN." },
      { en: "NEVER", es: "Nunca", ctx: "NEVER REMOVE SAFETY DEVICES DURING OPERATION.", ctxEs: "NUNCA RETIRE DISPOSITIVOS DE SEGURIDAD DURANTE LA OPERACIÓN." },
      { en: "IMMEDIATELY", es: "Inmediatamente", ctx: "IF YOU GET CHEMICAL ON YOUR SKIN, FLUSH IMMEDIATELY.", ctxEs: "SI RECIBE QUÍMICO EN LA PIEL, ENJUAGUE INMEDIATAMENTE." },
      { en: "CAREFUL", es: "Cuidadoso", ctx: "BE CAREFUL WHEN YOU REMOVE HEAVY COMPONENTS.", ctxEs: "SEA CUIDADOSO CUANDO RETIRE COMPONENTES PESADOS." },
      { en: "CAREFULLY", es: "Cuidadosamente", ctx: "CAREFULLY LIFT THE COVER TO PREVENT DAMAGE.", ctxEs: "LEVANTE CUIDADOSAMENTE LA CUBIERTA PARA PREVENIR DAÑO." },
      { en: "SLOWLY", es: "Lentamente", ctx: "SLOWLY RELEASE THE PRESSURE TO PREVENT INJURY.", ctxEs: "LIBERE LENTAMENTE LA PRESIÓN PARA PREVENIR LESIONES." }
    ]
  },
  {
    id: 22,
    title: "EVALUACIÓN DE RIESGO",
    desc: "Analizar, evaluar y mitigar riesgos antes del trabajo",
    color: "#34495e",
    words: [
      { en: "CHECK", es: "Verificar", ctx: "CHECK THAT ALL SAFETY DEVICES ARE INSTALLED BEFORE START.", ctxEs: "VERIFIQUE QUE TODOS LOS DISPOSITIVOS DE SEGURIDAD ESTÉN INSTALADOS ANTES DE INICIAR." },
      { en: "MAKE SURE", es: "Asegurarse", ctx: "MAKE SURE THAT THE AREA IS CLEAR BEFORE YOU START.", ctxEs: "ASEGÚRESE DE QUE EL ÁREA ESTÉ DESPEJADA ANTES DE INICIAR." },
      { en: "VERIFY", es: "Verificar", ctx: "VERIFY THAT ALL PERSONNEL ARE OUT OF THE DANGER AREA.", ctxEs: "VERIFIQUE QUE TODO EL PERSONAL ESTÉ FUERA DEL ÁREA DE PELIGRO." },
      { en: "CONFIRM", es: "Confirmar", ctx: "CONFIRM THAT THE SYSTEM IS DE-ENERGIZED BEFORE WORK.", ctxEs: "CONFIRME QUE EL SISTEMA ESTÁ DESENERGIZADO ANTES DEL TRABAJO." },
      { en: "INSPECT", es: "Inspeccionar", ctx: "INSPECT THE WORK AREA FOR HAZARDS BEFORE START.", ctxEs: "INSPECCIONE EL ÁREA DE TRABAJO EN BUSCA DE RIESGOS ANTES DE INICIAR." },
      { en: "EXAMINE", es: "Examinar", ctx: "EXAMINE THE SAFETY HARNESS FOR DAMAGE BEFORE USE.", ctxEs: "EXAMINE EL ARNÉS DE SEGURIDAD EN BUSCA DE DAÑO ANTES DE USAR." },
      { en: "PROBABILITY", es: "Probabilidad", ctx: "OBEY PRECAUTIONS TO DECREASE THE PROBABILITY OF FIRE.", ctxEs: "OBEDEZCA PRECAUCIONES PARA DISMINUIR LA PROBABILIDAD DE INCENDIO." },
      { en: "POSSIBLE", es: "Posible", ctx: "IF POSSIBLE, DO WORK IN A WELL-VENTILATED AREA.", ctxEs: "SI ES POSIBLE, HAGA EL TRABAJO EN UN ÁREA BIEN VENTILADA." },
      { en: "POTENTIAL", es: "Potencial", ctx: "PUT BARRIERS AROUND ALL POTENTIAL DANGER AREAS.", ctxEs: "COLOQUE BARRERAS ALREDEDOR DE TODAS LAS ÁREAS DE PELIGRO POTENCIAL." },
      { en: "LIKELY", es: "Probable", ctx: "IF A LEAK IS LIKELY, PUT A CONTAINER BELOW THE UNIT.", ctxEs: "SI UNA FUGA ES PROBABLE, COLOQUE UN CONTENEDOR DEBAJO DE LA UNIDAD." },
      { en: "UNLIKELY", es: "Improbable", ctx: "INJURY IS UNLIKELY IF YOU OBEY SAFETY INSTRUCTIONS.", ctxEs: "LA LESIÓN ES IMPROBABLE SI OBEDECE LAS INSTRUCCIONES DE SEGURIDAD." },
      { en: "ASSESS", es: "Evaluar", ctx: "ASSESS THE RISK BEFORE YOU START THE PROCEDURE.", ctxEs: "EVALÚE EL RIESGO ANTES DE INICIAR EL PROCEDIMIENTO." },
      { en: "ANALYZE", es: "Analizar", ctx: "ANALYZE THE HAZARD AND TAKE NECESSARY PRECAUTIONS.", ctxEs: "ANALICE EL RIESGO Y TOME LAS PRECAUCIONES NECESARIAS." },
      { en: "EVALUATE", es: "Evaluar", ctx: "EVALUATE THE SAFETY OF THE WORK AREA BEFORE START.", ctxEs: "EVALÚE LA SEGURIDAD DEL ÁREA DE TRABAJO ANTES DE INICIAR." },
      { en: "MITIGATE", es: "Mitigar", ctx: "MITIGATE RISK BY USING PROTECTIVE EQUIPMENT.", ctxEs: "MITIGUE EL RIESGO USANDO EQUIPO PROTECTOR." },
      { en: "CONTROL", es: "Controlar", ctx: "CONTROL THE HAZARD BY ISOLATING THE ENERGY SOURCE.", ctxEs: "CONTROLE EL RIESGO AISLANDO LA FUENTE DE ENERGÍA." }
    ]
  },
  {
    id: 23,
    title: "ACCIONES PROHIBIDAS",
    desc: "Reconocer y evitar comportamientos no permitidos",
    color: "#c0392b",
    words: [
      { en: "PROHIBITED", es: "Prohibido", ctx: "SMOKING IS PROHIBITED IN THE FUEL AREA.", ctxEs: "FUMAR ESTÁ PROHIBIDO EN EL ÁREA DE COMBUSTIBLE." },
      { en: "FORBIDDEN", es: "Prohibido", ctx: "ENTRY IS FORBIDDEN WITHOUT APPROVAL.", ctxEs: "LA ENTRADA ESTÁ PROHIBIDA SIN APROBACIÓN." },
      { en: "NOT PERMITTED", es: "No permitido", ctx: "REMOVAL OF SAFETY DEVICES IS NOT PERMITTED.", ctxEs: "LA REMOCIÓN DE DISPOSITIVOS DE SEGURIDAD NO ESTÁ PERMITIDA." },
      { en: "MUST NOT", es: "No debe", ctx: "YOU MUST NOT OPERATE THE SYSTEM WITHOUT TRAINING.", ctxEs: "USTED NO DEBE OPERAR EL SISTEMA SIN ENTRENAMIENTO." },
      { en: "SHALL NOT", es: "No deberá", ctx: "PERSONNEL SHALL NOT ENTER THE AREA WITHOUT PPE.", ctxEs: "EL PERSONAL NO DEBERÁ ENTRAR AL ÁREA SIN EPP." },
      { en: "DO NOT TOUCH", es: "No tocar", ctx: "DO NOT TOUCH ELECTRICAL COMPONENTS WITH WET HANDS.", ctxEs: "NO TOQUE COMPONENTES ELÉCTRICOS CON MANOS HÚMEDAS." },
      { en: "DO NOT OPEN", es: "No abrir", ctx: "DO NOT OPEN THE CONTAINER IF PRESSURE IS HIGH.", ctxEs: "NO ABRA EL CONTENEDOR SI LA PRESIÓN ES ALTA." },
      { en: "DO NOT REMOVE", es: "No retirar", ctx: "DO NOT REMOVE SAFETY LABELS FROM EQUIPMENT.", ctxEs: "NO RETIRE LAS ETIQUETAS DE SEGURIDAD DEL EQUIPO." },
      { en: "DO NOT BYPASS", es: "No puentear", ctx: "DO NOT BYPASS SAFETY INTERLOCKS ON MACHINERY.", ctxEs: "NO PUENTEE LOS INTERBLOQUEOS DE SEGURIDAD EN MAQUINARIA." },
      { en: "DO NOT IGNORE", es: "No ignorar", ctx: "DO NOT IGNORE WARNING SIGNS IN THE WORK AREA.", ctxEs: "NO IGNORE LAS SEÑALES DE ADVERTENCIA EN EL ÁREA DE TRABAJO." }
    ]
  }
];

export const GROUPS_TMA4: Group[] = [
  {
    id: 24,
    title: "ESTRUCTURA PRINCIPAL",
    desc: "Identificar componentes estructurales del fuselaje y ala",
    color: "#0284c7",
    words: [
      { en: "FUSELAGE", es: "Fuselaje", ctx: "THE FUSELAGE CONTAINS THE COCKPIT, CABIN, AND CARGO COMPARTMENTS.", ctxEs: "El fuselaje contiene la cabina de mando, la cabina de pasajeros y los compartimentos de carga." },
      { en: "WING", es: "Ala", ctx: "THE WING GENERATES LIFT DURING FLIGHT.", ctxEs: "El ala genera sustentación durante el vuelo." },
      { en: "EMPENNAGE", es: "Empenaje", ctx: "THE EMPENNAGE INCLUDES THE VERTICAL AND HORIZONTAL STABILIZERS.", ctxEs: "El empenaje incluye los estabilizadores vertical y horizontal." },
      { en: "SPAR", es: "Larguero", ctx: "THE SPAR IS THE PRIMARY STRUCTURAL MEMBER OF THE WING.", ctxEs: "El larguero es el elemento estructural principal del ala." },
      { en: "RIB", es: "Costilla", ctx: "RIBS GIVE THE WING ITS AERODYNAMIC SHAPE.", ctxEs: "Las costillas dan al ala su forma aerodinámica." },
      { en: "SKIN", es: "Revestimiento", ctx: "THE SKIN COVERS THE STRUCTURE AND PROVIDES A SMOOTH SURFACE.", ctxEs: "El revestimiento cubre la estructura y proporciona una superficie lisa." },
      { en: "STRINGER", es: "Larguerillo", ctx: "STRINGERS SUPPORT THE SKIN AND TRANSFER LOADS TO THE FRAMES.", ctxEs: "Los larguerillos soportan el revestimiento y transfieren cargas a los marcos." },
      { en: "BULKHEAD", es: "Mamparo", ctx: "THE BULKHEAD SEPARATES THE PRESSURIZED AND UNPRESSURIZED AREAS.", ctxEs: "El mamparo separa las áreas presurizadas y no presurizadas." },
      { en: "FRAME", es: "Cuaderna", ctx: "FRAMES GIVE THE FUSELAGE ITS CIRCULAR SHAPE.", ctxEs: "Las cuadernas dan al fuselaje su forma circular." },
      { en: "FAIRING", es: "Carenado", ctx: "FAIRINGS REDUCE AERODYNAMIC DRAG AT JUNCTIONS.", ctxEs: "Los carenados reducen la resistencia aerodinámica en las uniones." }
    ]
  },
  {
    id: 25,
    title: "SUPERFICIES DE CONTROL",
    desc: "Reconocer superficies móviles y sus funciones de control",
    color: "#0369a1",
    words: [
      { en: "AILERON", es: "Alerón", ctx: "THE AILERONS CONTROL THE ROLL OF THE AIRCRAFT.", ctxEs: "Los alerones controlan el alabeo de la aeronave." },
      { en: "ELEVATOR", es: "Elevador", ctx: "THE ELEVATORS CONTROL THE PITCH OF THE AIRCRAFT.", ctxEs: "Los elevadores controlan el cabeceo de la aeronave." },
      { en: "RUDDER", es: "Timón de dirección", ctx: "THE RUDDER CONTROLS THE YAW OF THE AIRCRAFT.", ctxEs: "El timón de dirección controla la guiñada de la aeronave." },
      { en: "FLAP", es: "Flap", ctx: "EXTEND THE FLAPS TO INCREASE LIFT DURING LANDING.", ctxEs: "Extienda los flaps para aumentar la sustentación durante el aterrizaje." },
      { en: "SLAT", es: "Slats", ctx: "SLATS EXTEND FROM THE LEADING EDGE TO IMPROVE LOW-SPEED PERFORMANCE.", ctxEs: "Los slats se extienden desde el borde de ataque para mejorar el rendimiento a baja velocidad." },
      { en: "SPOILER", es: "Spoiler", ctx: "SPOILERS DECREASE LIFT AND INCREASE DRAG.", ctxEs: "Los spoilers disminuyen la sustentación y aumentan la resistencia." },
      { en: "TRIM TAB", es: "Pestaña de ajuste", ctx: "ADJUST THE TRIM TAB TO REDUCE CONTROL FORCES.", ctxEs: "Ajuste la pestaña de ajuste para reducir las fuerzas de control." },
      { en: "SERVO TAB", es: "Pestaña servocompensadora", ctx: "THE SERVO TAB HELPS MOVE THE PRIMARY CONTROL SURFACE.", ctxEs: "La pestaña servocompensadora ayuda a mover la superficie de control primaria." }
    ]
  },
  {
    id: 26,
    title: "TREN DE ATERRIZAJE",
    desc: "Dominar componentes del tren, frenos y mecanismos",
    color: "#0f766e",
    words: [
      { en: "LANDING GEAR", es: "Tren de aterrizaje", ctx: "RETRACT THE LANDING GEAR AFTER TAKEOFF.", ctxEs: "Retraiga el tren de aterrizaje después del despegue." },
      { en: "STRUT", es: "Puntal", ctx: "THE STRUT ABSORBS SHOCKS DURING LANDING.", ctxEs: "El puntal absorbe los impactos durante el aterrizaje." },
      { en: "SHOCK ABSORBER", es: "Amortiguador", ctx: "THE SHOCK ABSORBER DECREASES THE IMPACT LOADS.", ctxEs: "El amortiguador disminuye las cargas de impacto." },
      { en: "WHEEL", es: "Rueda", ctx: "EXAMINE THE WHEEL FOR CRACKS AND WEAR.", ctxEs: "Examine la rueda en busca de grietas y desgaste." },
      { en: "BRAKE", es: "Freno", ctx: "APPLY THE BRAKES TO STOP THE AIRCRAFT.", ctxEs: "Aplique los frenos para detener la aeronave." },
      { en: "TIRE", es: "Neumático", ctx: "INFLATE THE TIRE TO THE SPECIFIED PRESSURE.", ctxEs: "Infle el neumático a la presión especificada." },
      { en: "RETRACTION MECHANISM", es: "Mecanismo de retracción", ctx: "THE RETRACTION MECHANISM MOVES THE GEAR UP AND DOWN.", ctxEs: "El mecanismo de retracción mueve el tren hacia arriba y hacia abajo." },
      { en: "ENGINE", es: "Motor", ctx: "THE ENGINE SUPPLIES THRUST FOR FLIGHT.", ctxEs: "El motor suministra empuje para el vuelo." },
      { en: "TURBINE", es: "Turbina", ctx: "THE TURBINE DRIVES THE COMPRESSOR AND ACCESSORIES.", ctxEs: "La turbina impulsa el compresor y los accesorios." },
      { en: "COMPRESSOR", es: "Compresor", ctx: "THE COMPRESSOR INCREASES THE PRESSURE OF THE INCOMING AIR.", ctxEs: "El compresor aumenta la presión del aire entrante." },
      { en: "COMBUSTOR", es: "Cámara de combustión", ctx: "FUEL BURNS IN THE COMBUSTOR TO PRODUCE HOT GASES.", ctxEs: "El combustible se quema en la cámara de combustión para producir gases calientes." },
      { en: "NOZZLE", es: "Tobera", ctx: "THE NOZZLE ACCELERATES THE EXHAUST GASES TO PRODUCE THRUST.", ctxEs: "La tobera acelera los gases de escape para producir empuje." },
      { en: "PROPELLER", es: "Hélice", ctx: "THE PROPELLER CONVERTS ENGINE POWER INTO THRUST.", ctxEs: "La hélice convierte la potencia del motor en empuje." },
      { en: "FAN", es: "Ventilador", ctx: "THE FAN SUPPLIES AIR TO THE BYPASS DUCT AND THE CORE ENGINE.", ctxEs: "El ventilador suministra aire al conducto de derivación y al núcleo del motor." },
      { en: "NACELLE", es: "Góndola", ctx: "THE NACELLE ENCLOSURES THE ENGINE AND ITS ACCESSORIES.", ctxEs: "La góndola encierra el motor y sus accesorios." },
      { en: "PYLON", es: "Pilón", ctx: "THE PYLON ATTACHES THE ENGINE TO THE WING.", ctxEs: "El pilón une el motor al ala." }
    ]
  },
  {
    id: 27,
    title: "SISTEMAS DE PROPULSIÓN",
    desc: "Comprender motores, turbinas y sistemas asociados",
    color: "#d97706",
    words: [
      { en: "HYDRAULIC PUMP", es: "Bomba hidráulica", ctx: "THE HYDRAULIC PUMP SUPPLIES PRESSURE TO THE SYSTEM.", ctxEs: "La bomba hidráulica suministra presión al sistema." },
      { en: "ACTUATOR", es: "Actuador", ctx: "THE ACTUATOR MOVES THE CONTROL SURFACES.", ctxEs: "El actuador mueve las superficies de control." },
      { en: "VALVE", es: "Válvula", ctx: "THE VALVE CONTROLS THE FLOW OF HYDRAULIC FLUID.", ctxEs: "La válvula controla el flujo de fluido hidráulico." },
      { en: "RESERVOIR", es: "Depósito", ctx: "THE RESERVOIR STORES HYDRAULIC FLUID FOR THE SYSTEM.", ctxEs: "El depósito almacena fluido hidráulico para el sistema." },
      { en: "ACCUMULATOR", es: "Acumulador", ctx: "THE ACCUMULATOR ABSORBS PRESSURE SURGES IN THE SYSTEM.", ctxEs: "El acumulador absorbe los picos de presión en el sistema." },
      { en: "FILTER", es: "Filtro", ctx: "THE FILTER REMOVES CONTAMINATION FROM THE HYDRAULIC FLUID.", ctxEs: "El filtro retira la contaminación del fluido hidráulico." },
      { en: "LINE", es: "Línea", ctx: "THE LINE CARRIES HYDRAULIC FLUID BETWEEN COMPONENTS.", ctxEs: "La línea transporta fluido hidráulico entre componentes." },
      { en: "FITTING", es: "Conexión", ctx: "THE FITTING CONNECTS THE LINE TO THE COMPONENT.", ctxEs: "La conexión une la línea al componente." },
      { en: "GENERATOR", es: "Generador", ctx: "THE GENERATOR SUPPLIES ELECTRICAL POWER TO THE AIRCRAFT.", ctxEs: "El generador suministra energía eléctrica a la aeronave." },
      { en: "ALTERNATOR", es: "Alternador", ctx: "THE ALTERNATOR CONVERTS MECHANICAL ENERGY TO ELECTRICAL ENERGY.", ctxEs: "El alternador convierte energía mecánica en energía eléctrica." },
      { en: "BUS BAR", es: "Barra colectora", ctx: "THE BUS BAR DISTRIBUTES ELECTRICAL POWER TO THE SYSTEMS.", ctxEs: "La barra colectora distribuye energía eléctrica a los sistemas." },
      { en: "CIRCUIT BREAKER", es: "Interruptor automático", ctx: "THE CIRCUIT BREAKER PROTECTS THE CIRCUIT FROM OVERLOAD.", ctxEs: "El interruptor automático protege el circuito de sobrecarga." },
      { en: "RELAY", es: "Relé", ctx: "THE RELAY CONTROLS THE FLOW OF ELECTRICAL CURRENT.", ctxEs: "El relé controla el flujo de corriente eléctrica." },
      { en: "SWITCH", es: "Interruptor", ctx: "SET THE SWITCH TO \"ON\" TO ENERGIZE THE SYSTEM.", ctxEs: "Ajuste el interruptor a \"ON\" para energizar el sistema." },
      { en: "CONNECTOR", es: "Conector", ctx: "THE CONNECTOR JOINS TWO ELECTRICAL WIRES.", ctxEs: "El conector une dos cables eléctricos." },
      { en: "WIRE", es: "Cable", ctx: "THE WIRE CARRIES ELECTRICAL CURRENT BETWEEN COMPONENTS.", ctxEs: "El cable transporta corriente eléctrica entre componentes." },
      { en: "FUEL TANK", es: "Tanque de combustible", ctx: "THE FUEL TANK STORES FUEL FOR THE ENGINE.", ctxEs: "El tanque de combustible almacena combustible para el motor." },
      { en: "FUEL PUMP", es: "Bomba de combustible", ctx: "THE FUEL PUMP SUPPLIES FUEL TO THE ENGINE.", ctxEs: "La bomba de combustible suministra combustible al motor." },
      { en: "FUEL VALVE", es: "Válvula de combustible", ctx: "THE FUEL VALVE CONTROLS THE FLOW OF FUEL.", ctxEs: "La válvula de combustible controla el flujo de combustible." },
      { en: "FUEL LINE", es: "Línea de combustible", ctx: "THE FUEL LINE CARRIES FUEL FROM THE TANK TO THE ENGINE.", ctxEs: "La línea de combustible transporta combustible desde el tanque al motor." },
      { en: "FUEL FILTER", es: "Filtro de combustible", ctx: "THE FUEL FILTER REMOVES CONTAMINATION FROM THE FUEL.", ctxEs: "El filtro de combustible retira la contaminación del combustible." },
      { en: "FUEL VENT", es: "Respiradero de combustible", ctx: "THE FUEL VENT PREVENTS PRESSURE BUILDUP IN THE TANK.", ctxEs: "El respiradero de combustible previene la acumulación de presión en el tanque." },
      { en: "FUEL GAUGE", es: "Indicador de combustible", ctx: "THE FUEL GAUGE SHOWS THE QUANTITY OF FUEL IN THE TANK.", ctxEs: "El indicador de combustible muestra la cantidad de combustible en el tanque." },
      { en: "QUANTITY INDICATOR", es: "Indicador de cantidad", ctx: "THE QUANTITY INDICATOR SHOWS THE AMOUNT OF FUEL REMAINING.", ctxEs: "El indicador de cantidad muestra la cantidad de combustible restante." }
    ]
  },
  {
    id: 28,
    title: "SISTEMAS HIDRÁULICOS",
    desc: "Identificar bombas, actuadores, válvulas y líneas",
    color: "#2563eb",
    words: [
      { en: "AIR CONDITIONING PACK", es: "Paquete de aire acondicionado", ctx: "THE PACK COOLS AND DEHUMIDIFIES THE CABIN AIR.", ctxEs: "El paquete enfría y deshumidifica el aire de la cabina." },
      { en: "OUTFLOW VALVE", es: "Válvula de descarga", ctx: "THE OUTFLOW VALVE CONTROLS CABIN PRESSURE.", ctxEs: "La válvula de descarga controla la presión de la cabina." },
      { en: "DUCT", es: "Conducto", ctx: "THE DUCT CARRIES CONDITIONED AIR TO THE CABIN.", ctxEs: "El conducto transporta aire acondicionado a la cabina." },
      { en: "PRESSURE CONTROLLER", es: "Controlador de presión", ctx: "THE PRESSURE CONTROLLER REGULATES CABIN ALTITUDE.", ctxEs: "El controlador de presión regula la altitud de la cabina." },
      { en: "HEAT EXCHANGER", es: "Intercambiador de calor", ctx: "THE HEAT EXCHANGER TRANSFERS HEAT BETWEEN FLUIDS.", ctxEs: "El intercambiador de calor transfiere calor entre fluidos." },
      { en: "COCKPIT", es: "Cabina de mando", ctx: "THE COCKPIT CONTAINS THE FLIGHT CONTROLS AND INSTRUMENTS.", ctxEs: "La cabina de mando contiene los controles de vuelo y los instrumentos." },
      { en: "CABIN", es: "Cabina de pasajeros", ctx: "THE CABIN CONTAINS THE PASSENGER SEATS AND AMENITIES.", ctxEs: "La cabina de pasajeros contiene los asientos y servicios para pasajeros." },
      { en: "CARGO COMPARTMENT", es: "Compartimento de carga", ctx: "THE CARGO COMPARTMENT STORES BAGGAGE AND FREIGHT.", ctxEs: "El compartimento de carga almacena equipaje y carga." },
      { en: "DOOR", es: "Puerta", ctx: "CLOSE THE DOOR AND MAKE SURE IT IS LOCKED.", ctxEs: "Cierre la puerta y asegúrese de que esté bloqueada." },
      { en: "WINDOW", es: "Ventana", ctx: "CLEAN THE WINDOW WITH A SOFT CLOTH.", ctxEs: "Limpie la ventana con un paño suave." },
      { en: "WINDSHIELD", es: "Parabrisas", ctx: "THE WINDSHIELD PROTECTS THE CREW FROM WIND AND DEBRIS.", ctxEs: "El parabrisas protege a la tripulación del viento y los escombros." },
      { en: "RADOME", es: "Radomo", ctx: "THE RADOME PROTECTS THE RADAR ANTENNA.", ctxEs: "El radomo protege la antena del radar." },
      { en: "STABILIZER", es: "Estabilizador", ctx: "THE STABILIZER PROVIDES LONGITUDINAL STABILITY.", ctxEs: "El estabilizador proporciona estabilidad longitudinal." },
      { en: "VERTICAL STABILIZER", es: "Estabilizador vertical", ctx: "THE VERTICAL STABILIZER PROVIDES DIRECTIONAL STABILITY.", ctxEs: "El estabilizador vertical proporciona estabilidad direccional." },
      { en: "HORIZONTAL STABILIZER", es: "Estabilizador horizontal", ctx: "THE HORIZONTAL STABILIZER CONTROLS PITCH.", ctxEs: "El estabilizador horizontal controla el cabeceo." },
      { en: "LEADING EDGE", es: "Borde de ataque", ctx: "THE LEADING EDGE IS THE FRONT EDGE OF THE WING.", ctxEs: "El borde de ataque es el borde frontal del ala." },
      { en: "TRAILING EDGE", es: "Borde de fuga", ctx: "THE TRAILING EDGE IS THE REAR EDGE OF THE WING.", ctxEs: "El borde de fuga es el borde trasero del ala." },
      { en: "WING TIP", es: "Punta de ala", ctx: "THE WING TIP REDUCES INDUCED DRAG.", ctxEs: "La punta de ala reduce la resistencia inducida." },
      { en: "WINGLET", es: "Winglet", ctx: "THE WINGLET IMPROVES FUEL EFFICIENCY.", ctxEs: "El winglet mejora la eficiencia de combustible." },
      { en: "FLAP TRACK", es: "Guía de flap", ctx: "THE FLAP TRACK GUIDES THE FLAP DURING EXTENSION.", ctxEs: "La guía de flap dirige el flap durante la extensión." },
      { en: "SLAT TRACK", es: "Guía de slat", ctx: "THE SLAT TRACK GUIDES THE SLAT DURING EXTENSION.", ctxEs: "La guía de slat dirige el slat durante la extensión." },
      { en: "CONTROL COLUMN", es: "Columna de control", ctx: "THE CONTROL COLUMN CONTROLS PITCH AND ROLL.", ctxEs: "La columna de control controla el cabeceo y el alabeo." },
      { en: "CONTROL WHEEL", es: "Volante de control", ctx: "TURN THE CONTROL WHEEL TO ROLL THE AIRCRAFT.", ctxEs: "Gire el volante de control para alabear la aeronave." },
      { en: "RUDDER PEDAL", es: "Pedal de timón", ctx: "PRESS THE RUDDER PEDAL TO CONTROL YAW.", ctxEs: "Presione el pedal de timón para controlar la guiñada." }
    ]
  },
  {
    id: 29,
    title: "SISTEMAS ELÉCTRICOS",
    desc: "Reconocer generadores, buses, interruptores y sensores",
    color: "#e11d48",
    words: [
      { en: "THROTTLE", es: "Acelerador", ctx: "SET THE THROTTLE TO THE DESIRED POWER SETTING.", ctxEs: "Ajuste el acelerador a la configuración de potencia deseada." },
      { en: "THRUST REVERSER", es: "Inversor de empuje", ctx: "THE THRUST REVERSER DECREASES LANDING DISTANCE.", ctxEs: "El inversor de empuje disminuye la distancia de aterrizaje." },
      { en: "NOSE GEAR", es: "Tren de nariz", ctx: "THE NOSE GEAR STEERS THE AIRCRAFT ON THE GROUND.", ctxEs: "El tren de nariz dirige la aeronave en tierra." },
      { en: "MAIN GEAR", es: "Tren principal", ctx: "THE MAIN GEAR SUPPORTS THE MAJOR WEIGHT OF THE AIRCRAFT.", ctxEs: "El tren principal soporta el peso mayor de la aeronave." },
      { en: "GEAR DOOR", es: "Puerta de tren", ctx: "THE GEAR DOOR COVERS THE LANDING GEAR WHEN RETRACTED.", ctxEs: "La puerta de tren cubre el tren de aterrizaje cuando está retraído." },
      { en: "UPLOCK", es: "Bloqueo superior", ctx: "THE UPLOCK HOLDS THE GEAR IN THE RETRACTED POSITION.", ctxEs: "El bloqueo superior sostiene el tren en la posición retraída." },
      { en: "DOWNLOCK", es: "Bloqueo inferior", ctx: "THE DOWNLOCK HOLDS THE GEAR IN THE EXTENDED POSITION.", ctxEs: "El bloqueo inferior sostiene el tren en la posición extendida." },
      { en: "TORQUE LINK", es: "Brazo de torsión", ctx: "THE TORQUE LINK PREVENTS ROTATION OF THE SHOCK STRUT.", ctxEs: "El brazo de torsión previene la rotación del amortiguador." },
      { en: "BRAKE DISC", es: "Disco de freno", ctx: "THE BRAKE DISC CONVERTS KINETIC ENERGY TO HEAT.", ctxEs: "El disco de freno convierte energía cinética en calor." },
      { en: "BRAKE PAD", es: "Pastilla de freno", ctx: "THE BRAKE PAD CONTACTS THE DISC TO CREATE FRICTION.", ctxEs: "La pastilla de freno contacta el disco para crear fricción." },
      { en: "BRAKE CALIPER", es: "Pinza de freno", ctx: "THE BRAKE CALIPER APPLIES PRESSURE TO THE PADS.", ctxEs: "La pinza de freno aplica presión a las pastillas." },
      { en: "ANTI-SKID SYSTEM", es: "Sistema antideslizante", ctx: "THE ANTI-SKID SYSTEM PREVENTS WHEEL LOCKUP.", ctxEs: "El sistema antideslizante previene el bloqueo de las ruedas." },
      { en: "TIRE PRESSURE", es: "Presión de neumático", ctx: "CHECK THE TIRE PRESSURE BEFORE FLIGHT.", ctxEs: "Verifique la presión del neumático antes del vuelo." },
      { en: "OLEO STRUT", es: "Pata oleoneumática", ctx: "THE OLEO STRUT ABSORBS LANDING IMPACTS.", ctxEs: "La pata oleoneumática absorbe los impactos de aterrizaje." },
      { en: "NOSE WHEEL STEERING", es: "Dirección de rueda de nariz", ctx: "THE NOSE WHEEL STEERING CONTROLS GROUND DIRECTION.", ctxEs: "La dirección de rueda de nariz controla la dirección en tierra." },
      { en: "THRUST LEVER", es: "Palanca de empuje", ctx: "MOVE THE THRUST LEVER TO CONTROL ENGINE POWER.", ctxEs: "Mueva la palanca de empuje para controlar la potencia del motor." },
      { en: "ENGINE COWL", es: "Carenado de motor", ctx: "THE ENGINE COWL COVERS THE ENGINE FOR AERODYNAMICS.", ctxEs: "El carenado de motor cubre el motor para aerodinámica." },
      { en: "AIR INTAKE", es: "Entrada de aire", ctx: "THE AIR INTAKE SUPPLIES AIR TO THE ENGINE.", ctxEs: "La entrada de aire suministra aire al motor." },
      { en: "EXHAUST NOZZLE", es: "Tobera de escape", ctx: "THE EXHAUST NOZZLE DIRECTS EXHAUST GASES.", ctxEs: "La tobera de escape dirige los gases de escape." },
      { en: "FUEL NOZZLE", es: "Inyector de combustible", ctx: "THE FUEL NOZZLE ATOMIZES FUEL FOR COMBUSTION.", ctxEs: "El inyector de combustible atomiza el combustible para la combustión." },
      { en: "IGNITER", es: "Encendedor", ctx: "THE IGNITER PROVIDES SPARK FOR ENGINE START.", ctxEs: "El encendedor proporciona chispa para el arranque del motor." },
      { en: "STARTER", es: "Arrancador", ctx: "THE STARTER ROTATES THE ENGINE FOR START.", ctxEs: "El arrancador gira el motor para el arranque." },
      { en: "OIL SYSTEM", es: "Sistema de aceite", ctx: "THE OIL SYSTEM LUBRICATES AND COOLS THE ENGINE.", ctxEs: "El sistema de aceite lubrica y enfría el motor." },
      { en: "OIL PUMP", es: "Bomba de aceite", ctx: "THE OIL PUMP CIRCULATES OIL THROUGH THE ENGINE.", ctxEs: "La bomba de aceite circula aceite a través del motor." }
    ]
  },
  {
    id: 30,
    title: "SISTEMAS DE COMBUSTIBLE",
    desc: "Dominar tanques, bombas, filtros e indicadores",
    color: "#4f46e5",
    words: [
      { en: "OIL COOLER", es: "Enfriador de aceite", ctx: "THE OIL COOLER DECREASES OIL TEMPERATURE.", ctxEs: "El enfriador de aceite disminuye la temperatura del aceite." },
      { en: "OIL FILTER", es: "Filtro de aceite", ctx: "THE OIL FILTER REMOVES PARTICLES FROM THE OIL.", ctxEs: "El filtro de aceite retira partículas del aceite." },
      { en: "OIL PRESSURE", es: "Presión de aceite", ctx: "MONITOR THE OIL PRESSURE DURING ENGINE OPERATION.", ctxEs: "Monitoree la presión de aceite durante la operación del motor." },
      { en: "OIL TEMPERATURE", es: "Temperatura de aceite", ctx: "MONITOR THE OIL TEMPERATURE DURING ENGINE OPERATION.", ctxEs: "Monitoree la temperatura de aceite durante la operación del motor." },
      { en: "COOLING SYSTEM", es: "Sistema de enfriamiento", ctx: "THE COOLING SYSTEM PREVENTS ENGINE OVERHEATING.", ctxEs: "El sistema de enfriamiento previene el sobrecalentamiento del motor." },
      { en: "VENTILATION SYSTEM", es: "Sistema de ventilación", ctx: "THE VENTILATION SYSTEM SUPPLIES FRESH AIR TO THE CABIN.", ctxEs: "El sistema de ventilación suministra aire fresco a la cabina." },
      { en: "PRESSURIZATION SYSTEM", es: "Sistema de presurización", ctx: "THE PRESSURIZATION SYSTEM MAINTAINS CABIN ALTITUDE.", ctxEs: "El sistema de presurización mantiene la altitud de la cabina." },
      { en: "OUTFLOW VALVE", es: "Válvula de descarga", ctx: "THE OUTFLOW VALVE REGULATES CABIN PRESSURE.", ctxEs: "La válvula de descarga regula la presión de la cabina." },
      { en: "SAFETY VALVE", es: "Válvula de seguridad", ctx: "THE SAFETY VALVE PREVENTS OVERPRESSURIZATION.", ctxEs: "La válvula de seguridad previene la sobrepresurización." },
      { en: "DUMP VALVE", es: "Válvula de descarga rápida", ctx: "THE DUMP VALVE RAPIDLY DEPRESSURIZES THE CABIN.", ctxEs: "La válvula de descarga rápida despresuriza rápidamente la cabina." },
      { en: "AIR CYCLE MACHINE", es: "Máquina de ciclo de aire", ctx: "THE AIR CYCLE MACHINE COOLS CABIN AIR.", ctxEs: "La máquina de ciclo de aire enfría el aire de la cabina." },
      { en: "PACK VALVE", es: "Válvula de paquete", ctx: "THE PACK VALVE CONTROLS AIRFLOW TO THE PACK.", ctxEs: "La válvula de paquete controla el flujo de aire al paquete." },
      { en: "MIXER UNIT", es: "Unidad mezcladora", ctx: "THE MIXER UNIT BLENDS HOT AND COLD AIR.", ctxEs: "La unidad mezcladora combina aire caliente y frío." },
      { en: "TEMPERATURE SENSOR", es: "Sensor de temperatura", ctx: "THE TEMPERATURE SENSOR MONITORS CABIN TEMPERATURE.", ctxEs: "El sensor de temperatura monitorea la temperatura de la cabina." },
      { en: "PRESSURE SENSOR", es: "Sensor de presión", ctx: "THE PRESSURE SENSOR MONITORS SYSTEM PRESSURE.", ctxEs: "El sensor de presión monitorea la presión del sistema." },
      { en: "FLOW SENSOR", es: "Sensor de flujo", ctx: "THE FLOW SENSOR MONITORS AIRFLOW RATE.", ctxEs: "El sensor de flujo monitorea la tasa de flujo de aire." },
      { en: "CONTROL UNIT", es: "Unidad de control", ctx: "THE CONTROL UNIT REGULATES SYSTEM OPERATION.", ctxEs: "La unidad de control regula la operación del sistema." },
      { en: "DISPLAY UNIT", es: "Unidad de visualización", ctx: "THE DISPLAY UNIT SHOWS SYSTEM STATUS.", ctxEs: "La unidad de visualización muestra el estado del sistema." },
      { en: "WARNING LIGHT", es: "Luz de advertencia", ctx: "THE WARNING LIGHT INDICATES A SYSTEM FAULT.", ctxEs: "La luz de advertencia indica una falla del sistema." },
      { en: "CAUTION LIGHT", es: "Luz de precaución", ctx: "THE CAUTION LIGHT INDICATES A NON-CRITICAL FAULT.", ctxEs: "La luz de precaución indica una falla no crítica." },
      { en: "MASTER WARNING", es: "Advertencia maestra", ctx: "THE MASTER WARNING ALERTS THE CREW TO URGENT CONDITIONS.", ctxEs: "La advertencia maestra alerta a la tripulación sobre condiciones urgentes." },
      { en: "MASTER CAUTION", es: "Precaución maestra", ctx: "THE MASTER CAUTION ALERTS THE CREW TO NON-URGENT CONDITIONS.", ctxEs: "La precaución maestra alerta a la tripulación sobre condiciones no urgentes." },
      { en: "ANNUNCIATOR PANEL", es: "Panel de anunciador", ctx: "THE ANNUNCIATOR PANEL DISPLAYS SYSTEM MESSAGES.", ctxEs: "El panel de anunciador muestra mensajes del sistema." },
      { en: "CIRCUIT", es: "Circuito", ctx: "THE CIRCUIT CARRIES ELECTRICAL CURRENT TO THE COMPONENT.", ctxEs: "El circuito transporta corriente eléctrica al componente." }
    ]
  },
  {
    id: 31,
    title: "AIRE ACONDICIONADO/PRESURIZACIÓN",
    desc: "Comprender packs, válvulas y control de cabina",
    color: "#0891b2",
    words: [
      { en: "GROUND", es: "Tierra", ctx: "THE GROUND PROVIDES A RETURN PATH FOR ELECTRICAL CURRENT.", ctxEs: "La tierra proporciona una ruta de retorno para la corriente eléctrica." },
      { en: "BUS", es: "Bus", ctx: "THE BUS DISTRIBUTES POWER TO MULTIPLE COMPONENTS.", ctxEs: "El bus distribuye energía a múltiples componentes." },
      { en: "TRANSFORMER", es: "Transformador", ctx: "THE TRANSFORMER CHANGES VOLTAGE LEVELS.", ctxEs: "El transformador cambia los niveles de voltaje." },
      { en: "RECTIFIER", es: "Rectificador", ctx: "THE RECTIFIER CONVERTS AC TO DC.", ctxEs: "El rectificador convierte CA a CC." },
      { en: "INVERTER", es: "Inversor", ctx: "THE INVERTER CONVERTS DC TO AC.", ctxEs: "El inversor convierte CC a CA." },
      { en: "BATTERY", es: "Batería", ctx: "THE BATTERY SUPPLIES EMERGENCY ELECTRICAL POWER.", ctxEs: "La batería suministra energía eléctrica de emergencia." },
      { en: "BATTERY CHARGER", es: "Cargador de batería", ctx: "THE BATTERY CHARGER MAINTAINS BATTERY CHARGE.", ctxEs: "El cargador de batería mantiene la carga de la batería." },
      { en: "CONTACTOR", es: "Contactor", ctx: "THE CONTACTOR CONNECTS OR DISCONNECTS ELECTRICAL CIRCUITS.", ctxEs: "El contactor conecta o desconecta circuitos eléctricos." },
      { en: "SOLENOID", es: "Solenoide", ctx: "THE SOLENOID OPERATES VALVES WITH ELECTRICAL POWER.", ctxEs: "El solenoide opera válvulas con energía eléctrica." },
      { en: "MOTOR", es: "Motor eléctrico", ctx: "THE MOTOR CONVERTS ELECTRICAL ENERGY TO MECHANICAL MOTION.", ctxEs: "El motor eléctrico convierte energía eléctrica en movimiento mecánico." },
      { en: "ACTUATOR MOTOR", es: "Motor de actuador", ctx: "THE ACTUATOR MOTOR MOVES CONTROL SURFACES.", ctxEs: "El motor de actuador mueve las superficies de control." },
      { en: "SERVO MOTOR", es: "Servomotor", ctx: "THE SERVO MOTOR PROVIDES PRECISE POSITION CONTROL.", ctxEs: "El servomotor proporciona control de posición preciso." },
      { en: "LIMIT SWITCH", es: "Interruptor de límite", ctx: "THE LIMIT SWITCH STOPS ACTUATOR TRAVEL.", ctxEs: "El interruptor de límite detiene el recorrido del actuador." },
      { en: "POSITION SENSOR", es: "Sensor de posición", ctx: "THE POSITION SENSOR REPORTS ACTUATOR POSITION.", ctxEs: "El sensor de posición reporta la posición del actuador." },
      { en: "FEEDBACK SENSOR", es: "Sensor de retroalimentación", ctx: "THE FEEDBACK SENSOR PROVIDES CLOSED-LOOP CONTROL.", ctxEs: "El sensor de retroalimentación proporciona control de lazo cerrado." },
      { en: "HYDRAULIC FLUID", es: "Fluido hidráulico", ctx: "THE HYDRAULIC FLUID TRANSMITS POWER IN THE SYSTEM.", ctxEs: "El fluido hidráulico transmite potencia en el sistema." },
      { en: "HYDRAULIC RESERVOIR", es: "Depósito hidráulico", ctx: "THE HYDRAULIC RESERVOIR STORES FLUID FOR THE SYSTEM.", ctxEs: "El depósito hidráulico almacena fluido para el sistema." },
      { en: "HYDRAULIC FILTER", es: "Filtro hidráulico", ctx: "THE HYDRAULIC FILTER REMOVES CONTAMINATION.", ctxEs: "El filtro hidráulico retira la contaminación." },
      { en: "HYDRAULIC LINE", es: "Línea hidráulica", ctx: "THE HYDRAULIC LINE CARRIES FLUID UNDER PRESSURE.", ctxEs: "La línea hidráulica transporta fluido bajo presión." },
      { en: "HYDRAULIC FITTING", es: "Conexión hidráulica", ctx: "THE HYDRAULIC FITTING CONNECTS LINES TO COMPONENTS.", ctxEs: "La conexión hidráulica une líneas a componentes." },
      { en: "HYDRAULIC HOSE", es: "Manguera hidráulica", ctx: "THE HYDRAULIC HOSE FLEXIBLY CONNECTS COMPONENTS.", ctxEs: "La manguera hidráulica conecta componentes de forma flexible." },
      { en: "HYDRAULIC COUPLING", es: "Acoplamiento hidráulico", ctx: "THE HYDRAULIC COUPLING ALLOWS QUICK CONNECTION.", ctxEs: "El acoplamiento hidráulico permite conexión rápida." },
      { en: "HYDRAULIC MANIFOLD", es: "Múltiple hidráulico", ctx: "THE HYDRAULIC MANIFOLD DISTRIBUTES FLUID TO MULTIPLE CIRCUITS.", ctxEs: "El múltiple hidráulico distribuye fluido a múltiples circuitos." },
      { en: "HYDRAULIC SELECTOR VALVE", es: "Válvula selectora hidráulica", ctx: "THE SELECTOR VALVE DIRECTS FLUID TO DIFFERENT ACTUATORS.", ctxEs: "La válvula selectora hidráulica dirige fluido a diferentes actuadores." }
    ]
  },
  {
    id: 32,
    title: "SISTEMAS DE SEGURIDAD Y EMERGENCIA",
    desc: "Identificar sistemas de oxígeno, fuego y advertencia",
    color: "#dc2626",
    words: [
      { en: "HYDRAULIC RELIEF VALVE", es: "Válvula de alivio hidráulica", ctx: "THE RELIEF VALVE PREVENTS OVERPRESSURE.", ctxEs: "La válvula de alivio hidráulica previene la sobrepresurización o picos de presión." },
      { en: "HYDRAULIC CHECK VALVE", es: "Válvula de retención hidráulica", ctx: "THE CHECK VALVE PREVENTS REVERSE FLOW.", ctxEs: "La válvula de retención hidráulica previene el flujo inverso." },
      { en: "HYDRAULIC SHUTOFF VALVE", es: "Válvula de cierre hidráulica", ctx: "THE SHUTOFF VALVE ISOLATES SYSTEM SECTIONS.", ctxEs: "La válvula de cierre hidráulica aísla secciones del sistema." },
      { en: "HYDRAULIC PRESSURE GAUGE", es: "Manómetro hidráulico", ctx: "THE GAUGE SHOWS SYSTEM PRESSURE.", ctxEs: "El manómetro muestra la presión del sistema." },
      { en: "HYDRAULIC TEMPERATURE GAUGE", es: "Termómetro hidráulico", ctx: "THE GAUGE SHOWS FLUID TEMPERATURE.", ctxEs: "El termómetro muestra la temperatura del fluido." },
      { en: "FUEL QUANTITY PROBE", es: "Sonda de cantidad de combustible", ctx: "THE PROBE MEASURES FUEL LEVEL IN THE TANK.", ctxEs: "La sonda mide el nivel de combustible en el tanque." },
      { en: "FUEL BOOST PUMP", es: "Bomba de refuerzo de combustible", ctx: "THE BOOST PUMP SUPPLIES FUEL TO THE ENGINE PUMP.", ctxEs: "La bomba de refuerzo de combustible suministra combustible a la bomba del motor." },
      { en: "FUEL CROSSFEED VALVE", es: "Válvula de transferencia cruzada de combustible", ctx: "THE CROSSFEED VALVE ALLOWS FUEL TRANSFER BETWEEN TANKS.", ctxEs: "La válvula de transferencia cruzada de combustible permite transferencia de combustible entre tanques." },
      { en: "FUEL JETTISON SYSTEM", es: "Sistema de vertido de combustible", ctx: "THE JETTISON SYSTEM DUMPS FUEL IN EMERGENCY.", ctxEs: "El sistema de vertido de combustible descarga combustible en emergencia." },
      { en: "FUEL HEATER", es: "Calentador de combustible", ctx: "THE FUEL HEATER PREVENTS ICE FORMATION.", ctxEs: "El calentador de combustible previene la formación de hielo." },
      { en: "FUEL WATER DETECTOR", es: "Detector de agua en combustible", ctx: "THE DETECTOR IDENTIFIES WATER IN FUEL.", ctxEs: "El detector identifica agua en combustible." },
      { en: "FUEL SAMPLER", es: "Muestreador de combustible", ctx: "THE SAMPLER COLLECTS FUEL FOR INSPECTION.", ctxEs: "El muestreador recolecta combustible para inspección." },
      { en: "FUEL DRAIN VALVE", es: "Válvula de drenaje de combustible", ctx: "THE DRAIN VALVE REMOVES WATER AND SEDIMENT.", ctxEs: "La válvula de drenaje de combustible retira agua y sedimentos." },
      { en: "FUEL FLOW INDICATOR", es: "Indicador de flujo de combustible", ctx: "THE INDICATOR SHOWS FUEL CONSUMPTION RATE.", ctxEs: "El indicador muestra la tasa de consumo de combustible." },
      { en: "FUEL PRESSURE INDICATOR", es: "Indicador de presión de combustible", ctx: "THE INDICATOR SHOWS FUEL SYSTEM PRESSURE.", ctxEs: "El indicador muestra la presión del sistema de combustible." },
      { en: "FUEL TEMPERATURE INDICATOR", es: "Indicador de temperatura de combustible", ctx: "THE INDICATOR SHOWS FUEL TEMPERATURE.", ctxEs: "El indicador muestra la temperatura del combustible." },
      { en: "CABIN PRESSURE INDICATOR", es: "Indicador de presión de cabina", ctx: "THE INDICATOR SHOWS CABIN ALTITUDE.", ctxEs: "El indicador muestra la altitud de la cabina." },
      { en: "CABIN ALTITUDE WARNING", es: "Advertencia de altitud de cabina", ctx: "THE WARNING ALERTS TO HIGH CABIN ALTITUDE.", ctxEs: "La advertencia alerta sobre altitud de cabina alta." },
      { en: "OXYGEN SYSTEM", es: "Sistema de oxígeno", ctx: "THE OXYGEN SYSTEM SUPPLIES BREATHING AIR.", ctxEs: "El sistema de oxígeno suministra aire para respirar." },
      { en: "OXYGEN MASK", es: "Máscara de oxígeno", ctx: "THE MASK DELIVERS OXYGEN TO THE USER.", ctxEs: "La máscara entrega oxígeno al usuario." },
      { en: "OXYGEN REGULATOR", es: "Regulador de oxígeno", ctx: "THE REGULATOR CONTROLS OXYGEN FLOW.", ctxEs: "El regulador controla el flujo de oxígeno." },
      { en: "OXYGEN CYLINDER", es: "Cilindro de oxígeno", ctx: "THE CYLINDER STORES COMPRESSED OXYGEN.", ctxEs: "El cilindro almacena oxígeno comprimido." },
      { en: "OXYGEN PRESSURE GAUGE", es: "Manómetro de oxígeno", ctx: "THE GAUGE SHOWS CYLINDER PRESSURE.", ctxEs: "El manómetro muestra la presión del cilindro." },
      { en: "EMERGENCY OXYGEN", es: "Oxígeno de emergencia", ctx: "THE EMERGENCY OXYGEN SUPPLIES CREW IN DECOMPRESSION.", ctxEs: "El oxígeno de emergencia suministra a la tripulación en descompresión." }
    ]
  },
  {
    id: 33,
    title: "SENSORES Y AVIÓNICA",
    desc: "Reconocer sondas, radares y sistemas de navegación",
    color: "#7c3aed",
    words: [
      { en: "FIRE DETECTION SYSTEM", es: "Sistema de detección de incendios", ctx: "THE SYSTEM DETECTS FIRE IN ENGINE BAYS.", ctxEs: "El sistema detecta incendios en bahías de motor." },
      { en: "FIRE EXTINGUISHER", es: "Extintor", ctx: "THE EXTINGUISHER SUPPRESSES FIRE.", ctxEs: "El extintor suprime el fuego." },
      { en: "FIRE BOTTLE", es: "Botella de extinción", ctx: "THE BOTTLE CONTAINS FIRE SUPPRESSION AGENT.", ctxEs: "La botella contiene agente de supresión de incendios." },
      { en: "FIRE DETECTOR LOOP", es: "Lazo detector de incendios", ctx: "THE LOOP SENSES TEMPERATURE INCREASES.", ctxEs: "El lazo detecta aumentos de temperatura." },
      { en: "FIRE WARNING LIGHT", es: "Luz de advertencia de incendio", ctx: "THE LIGHT ALERTS TO FIRE CONDITIONS.", ctxEs: "La luz alerta sobre condiciones de incendio." },
      { en: "FIRE HANDLE", es: "Manija de incendio", ctx: "THE HANDLE ACTIVATES FIRE SUPPRESSION.", ctxEs: "La manija activa la supresión de incendios." },
      { en: "ICE DETECTION SYSTEM", es: "Sistema de detección de hielo", ctx: "THE SYSTEM DETECTS ICE ACCUMULATION.", ctxEs: "El sistema detecta acumulación de hielo." },
      { en: "DE-ICE SYSTEM", es: "Sistema de deshielo", ctx: "THE DE-ICE SYSTEM REMOVES ICE FROM SURFACES.", ctxEs: "El sistema de deshielo retira hielo de las superficies." },
      { en: "ANTI-ICE SYSTEM", es: "Sistema anti-hielo", ctx: "THE ANTI-ICE SYSTEM PREVENTS ICE FORMATION.", ctxEs: "El sistema anti-hielo previene la formación de hielo." },
      { en: "HEATED PROBE", es: "Sonda calefactada", ctx: "THE HEATED PROBE PREVENTS ICE BLOCKAGE.", ctxEs: "La sonda calefactada previene bloqueo por hielo." },
      { en: "WING ANTI-ICE", es: "Anti-hielo de ala", ctx: "THE WING ANTI-ICE HEATS THE LEADING EDGE.", ctxEs: "El anti-hielo de ala calienta el borde de ataque." },
      { en: "ENGINE ANTI-ICE", es: "Anti-hielo de motor", ctx: "THE ENGINE ANTI-ICE PREVENTS ICE IN THE INTAKE.", ctxEs: "El anti-hielo de motor previene hielo en la entrada." },
      { en: "PITOT HEAT", es: "Calefacción Pitot", ctx: "THE PITOT HEAT PREVENTS ICE IN THE PITOT TUBE.", ctxEs: "La calefacción Pitot previene hielo en el tubo Pitot." },
      { en: "STATIC PORT", es: "Puerto estático", ctx: "THE STATIC PORT SENSES AMBIENT PRESSURE.", ctxEs: "El puerto estático siente la presión ambiental." },
      { en: "PITOT TUBE", es: "Tubo Pitot", ctx: "THE PITOT TUBE SENSES RAM AIR PRESSURE.", ctxEs: "El tubo Pitot siente la presión de aire de impacto." },
      { en: "ANGLE OF ATTACK SENSOR", es: "Sensor de ángulo de ataque", ctx: "THE SENSOR MEASURES ANGLE OF ATTACK.", ctxEs: "El sensor mide el ángulo de ataque." },
      { en: "TOTAL AIR TEMPERATURE PROBE", es: "Sonda de temperatura total de aire", ctx: "THE PROBE MEASURES TOTAL AIR TEMPERATURE.", ctxEs: "La sonda mide la temperatura total de aire." },
      { en: "DRAG CHUTE", es: "Paracaídas de frenado", ctx: "THE DRAG CHUTE DECREASES LANDING DISTANCE.", ctxEs: "El paracaídas de frenado disminuye la distancia de aterrizaje." },
      { en: "GROUND PROXIMITY WARNING SYSTEM", es: "Sistema de advertencia de proximidad al terreno", ctx: "THE GPWS ALERTS TO TERRAIN COLLISION RISK.", ctxEs: "El GPWS alerta sobre riesgo de colisión con el terreno." },
      { en: "TRAFFIC COLLISION AVOIDANCE SYSTEM", es: "Sistema de prevención de colisiones de tráfico", ctx: "THE TCAS ALERTS TO AIRCRAFT CONFLICTS.", ctxEs: "El TCAS alerta sobre conflictos con otras aeronaves." },
      { en: "WEATHER RADAR", es: "Radar meteorológico", ctx: "THE RADAR DETECTS WEATHER AHEAD OF THE AIRCRAFT.", ctxEs: "El radar detecta condiciones meteorológicas frente a la aeronave." },
      { en: "TRANSPONDER", es: "Transpondedor", ctx: "THE TRANSPONDER RESPONDS TO RADAR INTERROGATION.", ctxEs: "El transpondedor responde a la interrogación de radar." }
    ]
  }
];

